- comment_raw: "/**\n * @brief A special reservoir geometry that has an implanted\
    \ ohmic contact and\n *the rest of the channel extending to the left.\n **/"
  comment: '@brief A special reservoir geometry that has an implanted ohmic contact
    and

    the rest of the channel extending to the left.

    */'
  declaration: "class RightReservoirWithImplantedOhmic : public device_structures::Connection,\n\
    \                                         public HasImplantedOhmic,\n        \
    \                                 public HasLeftNeighbor {"
  kind: class
  name: null
