[build-system]
requires = [
  "setuptools >= 65.5.0",
  # "setuptools >= 68.1.0",
  "setuptools_scm",
]
build-backend = 'setuptools.build_meta'

[project]
name = "falcon_core"
maintainers = [
  { name = "FAlCon Core Developers", email = "falcon-support@falcon.com" },
]
description = "Core utilities for all falcon applications used for autotuning of quantum devices"
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.11",
  "Topic :: Scientific/Engineering",
]
version = "0.0.0"
license = { text = "MIT" }
requires-python = ">=3.11"
dependencies = [
  "numpy==1.25.2",
  "scipy==1.11.2",
  "pytest==8.2.1",
  "valkey==6.1.0",
  "setuptools-scm==8.1.0",
  "pytest-xdist==3.6.1",
  "dill==0.3.9",
]

[project.entry-points."core_messaging.plugins"]
acquisition_context = "falcon_core.autotuner_interfaces.contexts.acquisition_context"
base_context = "falcon_core.autotuner_interfaces.contexts.base_context"
measurement_context = "falcon_core.autotuner_interfaces.contexts.measurement_context"
interpretation_container = "falcon_core.autotuner_interfaces.interpretations.interpretation_container"
interpretation_context = "falcon_core.autotuner_interfaces.contexts.interpretation_context"
channel = "falcon_core.autotuner_interfaces.names.channel"
gname = "falcon_core.autotuner_interfaces.names.gname"
name_base = "falcon_core.autotuner_interfaces.names.name_base"
base_message = "falcon_core.communications.messages.base_message"
measurement_request = "falcon_core.communications.messages.measurement_request"
measurement_response = "falcon_core.communications.messages.measurement_response"
standard_request = "falcon_core.communications.messages.standard_request"
standard_response = "falcon_core.communications.messages.standard_response"
voltage_states_response = "falcon_core.communications.messages.voltage_states_response"
device_voltage_state = "falcon_core.communications.voltage_states.device_voltage_state"
device_voltage_states = "falcon_core.communications.voltage_states.device_voltage_states"
instrument_port = "falcon_core.instrument_interfaces.names.instrument_port"
knob = "falcon_core.instrument_interfaces.names.knob"
knobs = "falcon_core.instrument_interfaces.names.knobs"
meter = "falcon_core.instrument_interfaces.names.meter"
meters = "falcon_core.instrument_interfaces.names.meters"
ports = "falcon_core.instrument_interfaces.names.ports"
identity_transform = "falcon_core.instrument_interfaces.port_transforms.identity_transform"
port_transform = "falcon_core.instrument_interfaces.port_transforms.port_transform"
port_transforms = "falcon_core.instrument_interfaces.port_transforms.port_transforms"
base_cartesian_waveform = "falcon_core.instrument_interfaces.waveforms.base_cartesian_waveform"
base_waveform = "falcon_core.instrument_interfaces.waveforms.base_waveform"
cartesian_waveform = "falcon_core.instrument_interfaces.waveforms.cartesian_waveform"
cartesian_waveform_2D = "falcon_core.instrument_interfaces.waveforms.cartesian_waveform_2D"
cartesian_waveform_1D = "falcon_core.instrument_interfaces.waveforms.cartesian_waveform_1D"
waveform = "falcon_core.instrument_interfaces.waveforms.waveform"
instrument = "falcon_core.instrument_interfaces.instrument"
analytic_function = "falco_core.math.analytic_functions.analytic_function"
identity = "falcon_core.math.analytic_functions.identity"
validated_analytic_function = "falcon_core.math.analytic_functions.validated_analytic_function"
control_array = "falcon_core.math.arrays.control_array"
control_array_1D = "falcon_core.math.arrays.control_array_1D"
increasing_alignment = "falcon_core.math.arrays.increasing_alignment"
measured_array = "falcon_core.math.arrays.measured_array"
measured_array_1D = "falcon_core.math.arrays.measured_array_1D"
numpy_array_wrapper = "falcon_core.math.arrays.numpy_array_wrapper"
base_cartesian_discrete_space = "falcon_core.math.discrete_spaces.base_cartesian_discrete_space"
base_discrete_space = "falcon_core.math.discrete_spaces.base_discrete_space"
cartesian_discrete_space = "falcon_core.math.discrete_spaces.cartesian_discrete_space"
cartesian_discrete_space_2D = "falcon_core.math.discrete_spaces.cartesian_discrete_space_2D"
cartesian_discrete_space_1D = "falcon_core.math.discrete_spaces.cartesian_discrete_space_1D"
discrete_space = "falcon_core.math.discrete_spaces.discrete_space"
base_discretizer = "falcon_core.math.discretizers.base_discretizer"
cartesian_discretizer = "falcon_core.math.discretizers.cartesian_discretizer"
polar_discretizer = "falcon_core.math.discretizers.polar_discretizer"
base_coupled_labelled_domain = "falcon_core.math.domains.base_coupled_labelled_domain"
base_labelled_domain = "falcon_core.math.domains.base_labelled_domain"
coupled_knob_domain = "falcon_core.math.domains.coupled_knob_domain"
coupled_labelled_domain = "falcon_core.math.domains.coupled_labelled_domain"
domain = "falcon_core.math.domains.domain"
knob_domain = "falcon_core.math.domains.knob_domain"
labelled_domain = "falcon_core.math.domains.labelled_domain"
base_labelled_array = "falcon_core.math.labelled_arrays.base_labelled_array"
base_labelled_arrays = "falcon_core.math.labelled_arrays.base_labelled_arrays"
labelled_control_array = "falcon_core.math.labelled_arrays.labelled_control_array"
labelled_control_array_1D = "falcon_core.math.labelled_arrays.labelled_control_array_1D"
labelled_control_arrays = "falcon_core.math.labelled_arrays.labelled_control_arrays"
labelled_measured_array = "falcon_core.math.labelled_arrays.labelled_measured_array"
labelled_measured_array_1D = "falcon_core.math.labelled_arrays.labelled_measured_array_1D"
labelled_measured_arrays = "falcon_core.math.labelled_arrays.labelled_measured_arrays"
cartesian_1D_space = "falcon_core.math.spaces.cartesian_1D_space"
cartesian_2D_space = "falcon_core.math.spaces.cartesian_2D_space"
cartesian_space = "falcon_core.math.spaces.cartesian_space"
ray_space = "falcon_core.math.spaces.ray_space"
unit_space = "falcon_core.math.spaces.unit_space"
axes = "falcon_core.math.axes"
quantity = "falcon_core.math.quantity"
config = "falcon_core.physics.config.core.config"
group = "falcon_core.physics.config.core.group"
standard_config_connections = "falcon_core.physics.config.core.standard_config_connections"
barrier_gate_with_neighbors = "falcon_core.physics.config.geometries.barrier_gate_with_neighbors"
gate_geometry_array_1D = "falcon_core.physics.config.geometries.gate_geometry_array_1D"
has_implanted_ohmic = "falcon_core.physics.config.geometries.has_implanted_ohmic"
has_left_neighbor = "falcon_core.physics.config.geometries.has_left_neighbor"
has_right_neighbor = "falcon_core.physics.config.geometries.has_right_neighbor"
left_reservoir_with_implanted_ohmic = "falcon_core.physics.config.geometries.left_reservoir_with_implanted_ohmic"
plunger_gate_with_neighbors = "falcon_core.physics.config.geometries.plunger_gate_with_neighbors"
right_reservoir_with_implanted_ohmic = "falcon_core.physics.config.geometries.right_reservoir_with_implanted_ohmic"
barrier_gate = "falcon_core.physics.device_structures.barrier_gate"
base_connection = "falcon_core.physics.device_structures.base_connection"
dot_gate = "falcon_core.physics.device_structures.dot_gate"
gate = "falcon_core.physics.device_structures.gate"
gate_relations = "falcon_core.physics.device_structures.gate_relations"
impedance = "falcon_core.physics.device_structures.impedance"
ohmic = "falcon_core.physics.device_structures.ohmic"
plunger_gate = "falcon_core.physics.device_structures.plunger_gate"
reservoir_gate = "falcon_core.physics.device_structures.reservoir_gate"
screening_gate = "falcon_core.physics.device_structures.screening_gate"
symbol_unit = "falcon_core.physics.units.symbol_unit"
unit = "falcon_core.physics.units.unit"


[project.readme]
file = "README.rst"
content-type = "text/x-rst"

# [project.urls]
# Homepage = "https://github.com/microsoft/Qcodes"
# Documentation = "https://microsoft.github.io/Qcodes/"
# Source = "https://github.com/microsoft/qcodes"
# Tracker = "https://github.com/microsoft/Qcodes/issues"
# Changelog = "https://microsoft.github.io/Qcodes/changes/index.html"

[tool.setuptools_scm]
version_scheme = "post-release"
[tool.coverage.run]
omit = ["src/falcon/__init__.py", "*/__init__.py"]
[tool.coverage.report]
exclude_lines = ["pragma: no cover", "if TYPE_CHECKING:"]

# we ignore warnings
# triggered by third party packages
# and error on all other warnings
filterwarnings = [
  'error',
  'ignore:Deprecated call to `pkg_resources\.declare_namespace:DeprecationWarning',                                               # google, sphinxcontrib
  'ignore:pkg_resources is deprecated as an API:DeprecationWarning',                                                              # pyvisa-sim
  'ignore:open_binary is deprecated:DeprecationWarning',                                                                          # pyvisa-sim
  'ignore:datetime.datetime.utcfromtimestamp\(\) is deprecated and scheduled for removal in a future version:DeprecationWarning', # tqdm dateutil
  'ignore:Jupyter is migrating its paths to use standard platformdirs:DeprecationWarning',                                        # jupyter
  'ignore:Parsing dates involving a day of month without a year specified is ambiguious:DeprecationWarning',                      # ipykernel 3.13+
  'ignore:unclosed database in:ResourceWarning',                                                                                  # internal should be fixed
]

# known-first-party = ["falcon"]

# TID253 these imports are fine at module level
# in tests and examples
"docs/*" = ["TID253"]
"tests/*" = ["TID253"]


[tool.setuptools.packages.find]
# All the following settings are optional:
where = ["src"]       # ["."] by default
include = ["falcon*"] # ["*"] by default
exclude = []          # empty by default
namespaces = false    # true by default

[tool.pytest.ini_options]
# addopts="-n 5 --dist worksteal"

[tool.mypy]
strict_optional = true
incremental = true
cache_dir = ".mypy_cache"
show_column_numbers = true
plugins = "numpy.typing.mypy_plugin"
show_error_codes = true
enable_error_code = "ignore-without-code"
# strict confic. Eventually we would like to
# turn all of these on. These are all setings
# turned on by strict as of mypy 0.971
warn_unused_configs = true
# waiting for variadic generics so we
# can type numpy array constructors
disallow_any_generics = false
# we subclass non typed classes (from ipython / wrapt)
disallow_subclassing_any = false
# we are calling into untyped code from 3th parties
disallow_untyped_calls = false
disallow_untyped_defs = true
disallow_incomplete_defs = true
# triggers warnings in untyped code
check_untyped_defs = false
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
# this triggers failures due to returning
# values from untyped 3th party libs
warn_return_any = false
no_implicit_reexport = true
strict_equality = true

[[tool.mypy.overrides]]
module = ["tests.*"]
disallow_untyped_defs = false
disallow_incomplete_defs = false

[tool.ruff]
line-length = 88

