- comment_raw: "/**\n * @brief This a graph representation of the connections between\
    \ gates in a\n * quantum dot device.\n **/"
  comment: '@brief This a graph representation of the connections between gates in
    a

    quantum dot device.

    */'
  declaration: 'class Adjacency : public generic::FArray<int> {'
  kind: class
  name: null
- comment_raw: "/**\n   # @brief Returns the indexes of the gates in the order for\
    \ the adjacency\n   matrix\n  */"
  comment: "# @brief Returns the indexes of the gates in the order for the adjacency\n\
    \   matrix"
  declaration: Indexes indexes() const;
  kind: function
  name: falcon_core::physics::config::core::Adjacency::indexes
- comment_raw: "/**\n   * @brief Returns the pairs of indexes where the adjacency\
    \ matrix is true (1)\n   */"
  comment: '@brief Returns the pairs of indexes where the adjacency matrix is true
    (1)'
  declaration: std::vector<std::pair<size_t, size_t>> get_true_pairs() const;
  kind: function
  name: falcon_core::physics::config::core::Adjacency::get_true_pairs
