- comment_raw: "/**\n * @brief Contains a ready to use voltage constrains matrix and\
    \ matching limits\n * for each constraint.\n */"
  comment: '@brief Contains a ready to use voltage constrains matrix and matching
    limits

    for each constraint.'
  declaration: 'class VoltageConstraints : public generic::Song {'
  kind: class
  name: null
- comment_raw: "/**\n   * @brief The constraint matrix.\n   */"
  comment: '@brief The constraint matrix.'
  declaration: const generic::FArray<double>& matrix() const;
  kind: function
  name: falcon_core::physics::config::core::VoltageConstraints::matrix
- comment_raw: "/**\n   * @brief The constraint matrix.\n   */"
  comment: '@brief The constraint matrix.'
  declaration: const generic::FArray<double>& matrix();
  kind: function
  name: falcon_core::physics::config::core::VoltageConstraints::matrix
- comment_raw: "/**\n   * @brief The adjacency matrix used to understand the device\
    \ layout.\n   */"
  comment: '@brief The adjacency matrix used to understand the device layout.'
  declaration: const AdjacencySP adjacency() const;
  kind: function
  name: falcon_core::physics::config::core::VoltageConstraints::adjacency
- comment_raw: "/**\n   * @brief The y axis vector safe voltage limits for each constraint.\n\
    \   */"
  comment: '@brief The y axis vector safe voltage limits for each constraint.'
  declaration: const generic::FArray<double>& limits() const;
  kind: function
  name: falcon_core::physics::config::core::VoltageConstraints::limits
