c_header: VoltageConstraints_c_api.h
cpp_headers:
- ../../../../../../cpp/include/falcon_core/physics/config/core/VoltageConstraints.hpp
mappings:
- cpp: falcon_core::physics::config::core::VoltageConstraints::matrix
  c: VoltageConstraints_matrix
- cpp: falcon_core::physics::config::core::VoltageConstraints::matrix
  c: VoltageConstraints_matrix
- cpp: falcon_core::physics::config::core::VoltageConstraints::adjacency
  c: VoltageConstraints_adjacency
- cpp: falcon_core::physics::config::core::VoltageConstraints::limits
  c: VoltageConstraints_limits
