- comment_raw: "/**\n * @brief A gate with an ohmic below it.\n */"
  comment: '@brief A gate with an ohmic below it.'
  declaration: 'class HasImplantedOhmic : public virtual generic::Song {'
  kind: class
  name: null
- comment_raw: "/**\n   * @brief Returns the ohmic below the gate.\n   */"
  comment: '@brief Returns the ohmic below the gate.'
  declaration: device_structures::ConnectionSP ohmic() const;
  kind: function
  name: falcon_core::physics::config::geometries::HasImplantedOhmic::ohmic
