#pragma once
#ifdef __cplusplus
    extern "C" {
#endif
#include "falcon_core/generic/PairQuantityQuantity_c_api.h"
#include <cstddef>

// Forward declarations for opaque handles
typedef void* ListPairQuantityQuantityHandle;
// Function declarations

ListPairQuantityQuantityHandle ListPairQuantityQuantity_create_empty();
ListPairQuantityQuantityHandle ListPairQuantityQuantity_allocate(size_t count);
ListPairQuantityQuantityHandle ListPairQuantityQuantity_fill_value(size_t count, PairQuantityQuantityHandle value);
ListPairQuantityQuantityHandle ListPairQuantityQuantity_create(const PairQuantityQuantityHandle* data, size_t count);
void ListPairQuantityQuantity_destroy(ListPairQuantityQuantityHandle handle);
void ListPairQuantityQuantity_push_back(ListPairQuantityQuantityHandle handle, PairQuantityQuantityHandle value);
size_t ListPairQuantityQuantity_size(ListPairQuantityQuantityHandle handle);
bool ListPairQuantityQuantity_empty(ListPairQuantityQuantityHandle handle);
void ListPairQuantityQuantity_erase_at(ListPairQuantityQuantityHandle handle, size_t idx);
void ListPairQuantityQuantity_clear(ListPairQuantityQuantityHandle handle);
PairQuantityQuantityHandle ListPairQuantityQuantity_at(ListPairQuantityQuantityHandle handle, size_t idx);
size_t ListPairQuantityQuantity_items(ListPairQuantityQuantityHandle handle, PairQuantityQuantityHandle* out_buffer, size_t buffer_size);
bool ListPairQuantityQuantity_contains(ListPairQuantityQuantityHandle handle, PairQuantityQuantityHandle value);
size_t ListPairQuantityQuantity_index(ListPairQuantityQuantityHandle handle, PairQuantityQuantityHandle value);
ListPairQuantityQuantityHandle ListPairQuantityQuantity_intersection(ListPairQuantityQuantityHandle handle, ListPairQuantityQuantityHandle other);
bool ListPairQuantityQuantity_equal(ListPairQuantityQuantityHandle a, ListPairQuantityQuantityHandle b);
bool ListPairQuantityQuantity_not_equal(ListPairQuantityQuantityHandle a, ListPairQuantityQuantityHandle b);
#ifdef __cplusplus
}
#endif