c_header: Config_c_api.h
cpp_headers:
- ../../../../../../cpp/include/falcon_core/physics/config/core/Config.hpp
mappings:
- cpp: falcon_core::physics::config::core::Config::num_unique_channels
  c: Config_num_unique_channels
- cpp: falcon_core::physics::config::core::Config::voltage_constraints
  c: Config_voltage_constraints
- cpp: falcon_core::physics::config::core::Config::groups
  c: Config_groups
- cpp: falcon_core::physics::config::core::Config::channels
  c: Config_channels
- cpp: falcon_core::physics::config::core::Config::get_impedance
  c: Config_get_impedance
- cpp: falcon_core::physics::config::core::Config::get_all_gnames
  c: Config_get_all_gnames
- cpp: falcon_core::physics::config::core::Config::get_all_groups
  c: Config_get_all_groups
- cpp: falcon_core::physics::config::core::Config::has_channel
  c: Config_has_channel
- cpp: falcon_core::physics::config::core::Config::has_gname
  c: Config_has_gname
- cpp: falcon_core::physics::config::core::Config::select_group
  c: Config_select_group
- cpp: falcon_core::physics::config::core::Config::get_dot_number
  c: Config_get_dot_number
- cpp: falcon_core::physics::config::core::Config::get_charge_sense_groups
  c: Config_get_charge_sense_groups
- cpp: falcon_core::physics::config::core::Config::ohmic_in_charge_sensor
  c: Config_ohmic_in_charge_sensor
- cpp: falcon_core::physics::config::core::Config::get_associated_ohmic
  c: Config_get_associated_ohmic
- cpp: falcon_core::physics::config::core::Config::get_current_channels
  c: Config_get_current_channels
- cpp: falcon_core::physics::config::core::Config::get_gname
  c: Config_get_gname
- cpp: falcon_core::physics::config::core::Config::get_group_barrier_gates
  c: Config_get_group_barrier_gates
- cpp: falcon_core::physics::config::core::Config::get_group_plunger_gates
  c: Config_get_group_plunger_gates
- cpp: falcon_core::physics::config::core::Config::get_group_reservoir_gates
  c: Config_get_group_reservoir_gates
- cpp: falcon_core::physics::config::core::Config::get_group_screening_gates
  c: Config_get_group_screening_gates
- cpp: falcon_core::physics::config::core::Config::get_group_dot_gates
  c: Config_get_group_dot_gates
- cpp: falcon_core::physics::config::core::Config::get_group_gates
  c: Config_get_group_gates
- cpp: falcon_core::physics::config::core::Config::get_channel_barrier_gates
  c: Config_get_channel_barrier_gates
- cpp: falcon_core::physics::config::core::Config::get_channel_plunger_gates
  c: Config_get_channel_plunger_gates
- cpp: falcon_core::physics::config::core::Config::get_channel_reservoir_gates
  c: Config_get_channel_reservoir_gates
- cpp: falcon_core::physics::config::core::Config::get_channel_screening_gates
  c: Config_get_channel_screening_gates
- cpp: falcon_core::physics::config::core::Config::get_channel_dot_gates
  c: Config_get_channel_dot_gates
- cpp: falcon_core::physics::config::core::Config::get_channel_gates
  c: Config_get_channel_gates
- cpp: falcon_core::physics::config::core::Config::get_channel_ohmics
  c: Config_get_channel_ohmics
- cpp: falcon_core::physics::config::core::Config::get_channel_order_no_ohmics
  c: Config_get_channel_order_no_ohmics
- cpp: falcon_core::physics::config::core::Config::get_num_unique_channels
  c: Config_get_num_unique_channels
- cpp: falcon_core::physics::config::core::Config::return_channels_from_gate
  c: Config_return_channels_from_gate
- cpp: falcon_core::physics::config::core::Config::return_channel_from_gate
  c: Config_return_channel_from_gate
- cpp: falcon_core::physics::config::core::Config::ohmic_in_channel
  c: Config_ohmic_in_channel
- cpp: falcon_core::physics::config::core::Config::get_dot_channel_neighbors
  c: Config_get_dot_channel_neighbors
- cpp: falcon_core::physics::config::core::Config::get_barrier_gate_dict
  c: Config_get_barrier_gate_dict
- cpp: falcon_core::physics::config::core::Config::get_plunger_gate_dict
  c: Config_get_plunger_gate_dict
- cpp: falcon_core::physics::config::core::Config::get_reservoir_gate_dict
  c: Config_get_reservoir_gate_dict
- cpp: falcon_core::physics::config::core::Config::get_screening_gate_dict
  c: Config_get_screening_gate_dict
- cpp: falcon_core::physics::config::core::Config::get_dot_gate_dict
  c: Config_get_dot_gate_dict
- cpp: falcon_core::physics::config::core::Config::get_gate_dict
  c: Config_get_gate_dict
- cpp: falcon_core::physics::config::core::Config::get_isolated_barrier_gates
  c: Config_get_isolated_barrier_gates
- cpp: falcon_core::physics::config::core::Config::get_isolated_plunger_gates
  c: Config_get_isolated_plunger_gates
- cpp: falcon_core::physics::config::core::Config::get_isolated_reservoir_gates
  c: Config_get_isolated_reservoir_gates
- cpp: falcon_core::physics::config::core::Config::get_isolated_screening_gates
  c: Config_get_isolated_screening_gates
- cpp: falcon_core::physics::config::core::Config::get_isolated_dot_gates
  c: Config_get_isolated_dot_gates
- cpp: falcon_core::physics::config::core::Config::get_isolated_gates
  c: Config_get_isolated_gates
- cpp: falcon_core::physics::config::core::Config::get_shared_barrier_gates
  c: Config_get_shared_barrier_gates
- cpp: falcon_core::physics::config::core::Config::get_shared_plunger_gates
  c: Config_get_shared_plunger_gates
- cpp: falcon_core::physics::config::core::Config::get_shared_reservoir_gates
  c: Config_get_shared_reservoir_gates
- cpp: falcon_core::physics::config::core::Config::get_shared_screening_gates
  c: Config_get_shared_screening_gates
- cpp: falcon_core::physics::config::core::Config::get_shared_dot_gates
  c: Config_get_shared_dot_gates
- cpp: falcon_core::physics::config::core::Config::get_shared_gates
  c: Config_get_shared_gates
- cpp: falcon_core::physics::config::core::Config::get_shared_channel_barrier_gates
  c: Config_get_shared_channel_barrier_gates
- cpp: falcon_core::physics::config::core::Config::get_shared_channel_plunger_gates
  c: Config_get_shared_channel_plunger_gates
- cpp: falcon_core::physics::config::core::Config::get_shared_channel_reservoir_gates
  c: Config_get_shared_channel_reservoir_gates
- cpp: falcon_core::physics::config::core::Config::get_shared_channel_screening_gates
  c: Config_get_shared_channel_screening_gates
- cpp: falcon_core::physics::config::core::Config::get_shared_channel_dot_gates
  c: Config_get_shared_channel_dot_gates
- cpp: falcon_core::physics::config::core::Config::get_shared_channel_gates
  c: Config_get_shared_channel_gates
- cpp: falcon_core::physics::config::core::Config::get_isolated_channel_barrier_gates
  c: Config_get_isolated_channel_barrier_gates
- cpp: falcon_core::physics::config::core::Config::get_isolated_channel_plunger_gates
  c: Config_get_isolated_channel_plunger_gates
- cpp: falcon_core::physics::config::core::Config::get_isolated_channel_reservoir_gates
  c: Config_get_isolated_channel_reservoir_gates
- cpp: falcon_core::physics::config::core::Config::get_isolated_channel_screening_gates
  c: Config_get_isolated_channel_screening_gates
- cpp: falcon_core::physics::config::core::Config::get_isolated_channel_dot_gates
  c: Config_get_isolated_channel_dot_gates
- cpp: falcon_core::physics::config::core::Config::get_isolated_channel_gates
  c: Config_get_isolated_channel_gates
- cpp: falcon_core::physics::config::core::Config::get_isolated_barrier_gates_by_channel
  c: Config_get_isolated_barrier_gates_by_channel
- cpp: falcon_core::physics::config::core::Config::get_isolated_plunger_gates_by_channel
  c: Config_get_isolated_plunger_gates_by_channel
- cpp: falcon_core::physics::config::core::Config::get_isolated_reservoir_gates_by_channel
  c: Config_get_isolated_reservoir_gates_by_channel
- cpp: falcon_core::physics::config::core::Config::get_isolated_screening_gates_by_channel
  c: Config_get_isolated_screening_gates_by_channel
- cpp: falcon_core::physics::config::core::Config::get_isolated_dot_gates_by_channel
  c: Config_get_isolated_dot_gates_by_channel
- cpp: falcon_core::physics::config::core::Config::get_isolated_gates_by_channel
  c: Config_get_isolated_gates_by_channel
- cpp: falcon_core::physics::config::core::Config::generate_gate_relations
  c: Config_generate_gate_relations
