package main

import (
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
	"golang.org/x/text/cases"
	"golang.org/x/text/language"
	"gopkg.in/yaml.v3"
)

type Command struct {
	Name        string               `yaml:"name"`
	Version     string               `yaml:"version"`
	Description string               `yaml:"description"`
	Parameters  map[string]Parameter `yaml:"parameters"`
}

type Parameter struct {
	Type        interface{} `yaml:"type"`
	Required    bool        `yaml:"required"`
	Description string      `yaml:"description"`
	Items       interface{} `yaml:"items,omitempty"`
}

func goType(yamlType interface{}, items interface{}) string {
	switch t := yamlType.(type) {
	case string:
		switch t {
		case "string":
			return "string"
		case "integer":
			return "int"
		case "float":
			return "float64"
		case "json":
			return "map[string]interface{}"
		case "array":
			if items != nil {
				return "[]" + goType(items, nil)
			}
			return "[]interface{}"
		default:
			return "interface{}"
		}
	case []interface{}:
		return "interface{}"
	default:
		return "interface{}"
	}
}

func toExported(name string) string {
	c := cases.Title(language.English)
	parts := strings.Split(name, "_")
	for i, p := range parts {
		parts[i] = c.String(p)
	}
	return strings.Join(parts, "")
}

func loadCommonContent(commonDir string) (string, error) {
	var commonContent strings.Builder
	files, err := filepath.Glob(filepath.Join(commonDir, "*.yaml"))
	if err != nil {
		return "", err
	}
	for _, file := range files {
		data, err := os.ReadFile(file)
		if err != nil {
			fmt.Printf("Failed to read common file %s: %v\n", file, err)
			continue
		}
		fmt.Printf("Loaded common file: %s\n", file)
		commonContent.Write(data)
		commonContent.WriteString("\n")
	}
	return commonContent.String(), nil
}

func generate(commandsDir, commonDir, outputFile, packageName string) error {
	commonContent, err := loadCommonContent(commonDir)
	if err != nil {
		return fmt.Errorf("failed to load common YAML: %w", err)
	}

	files, err := filepath.Glob(filepath.Join(commandsDir, "*.yaml"))
	if err != nil {
		return err
	}

	var commands []Command

	for _, file := range files {
		fmt.Printf("Processing file: %s\n", file)
		data, err := os.ReadFile(file)
		if err != nil {
			log.Printf("Failed to read %s: %v", file, err)
			continue
		}
		combined := []byte(commonContent + string(data))
		var cmd Command
		if err := yaml.Unmarshal(combined, &cmd); err != nil {
			log.Printf("Failed to parse %s: %v", file, err)
			continue
		}
		if cmd.Name == "" {
			fmt.Printf("Warning: Command in file %s has no name\n", file)
			continue
		}
		fmt.Printf("Parsed command: %s\n", cmd.Name)
		commands = append(commands, cmd)
	}
	fmt.Printf("Total commands parsed: %d\n", len(commands))

	var out strings.Builder
	fmt.Fprintf(&out, "// Code generated by gen_commands.go; DO NOT EDIT.\n")
	fmt.Fprintf(&out, "package %s\n\n", packageName)
	fmt.Fprintf(&out, "/*\nThis file is auto-generated from YAML command schemas.\n*/\n\n")

	for _, cmd := range commands {
		structName := toExported(cmd.Name) + "Command"
		fmt.Printf("Generating struct for command: %s\n", cmd.Name)
		fmt.Fprintf(&out, "// %s: %s\n", structName, cmd.Description)
		fmt.Fprintf(&out, "type %s struct {\n", structName)
		for paramName, param := range cmd.Parameters {
			fieldName := toExported(paramName)
			fieldType := goType(param.Type, param.Items)
			tag := fmt.Sprintf("`yaml:\"%s\" json:\"%s\"`", paramName, paramName)
			fmt.Fprintf(&out, "    %s %s %s // %s\n", fieldName, fieldType, tag, param.Description)
		}
		fmt.Fprintf(&out, "}\n\n")
	}

	fmt.Fprintf(&out, "// CommandRegistry maps command names to empty struct instances\n")
	fmt.Fprintf(&out, "var CommandRegistry = map[string]interface{}{\n")
	for _, cmd := range commands {
		structName := toExported(cmd.Name) + "Command"
		fmt.Fprintf(&out, "    \"%s\": %s{},\n", cmd.Name, structName)
	}
	fmt.Fprintf(&out, "}\n")

	if err := os.WriteFile(outputFile, []byte(out.String()), 0644); err != nil {
		return fmt.Errorf("failed to write output: %w", err)
	}
	return nil
}

func main() {
	var (
		commandsDir string
		commonDir   string
		outputFile  string
		packageName string
	)

	rootCmd := &cobra.Command{
		Use:   "gencommands",
		Short: "Generate Go structs from YAML command schemas",
		Run: func(cmd *cobra.Command, args []string) {
			if err := generate(commandsDir, commonDir, outputFile, packageName); err != nil {
				fmt.Fprintf(os.Stderr, "Error: %v\n", err)
			}
			fmt.Printf("Generated %s from %s and %s\n", outputFile, commandsDir, commonDir)
		},
	}

	rootCmd.Flags().StringVar(&commandsDir, "commands-dir", "api/commands/v1", "Directory containing command YAML files")
	rootCmd.Flags().StringVar(&commonDir, "common-dir", "api/common", "Directory containing common YAML files")
	rootCmd.Flags().StringVar(&outputFile, "output", "commands_gen.go", "Output Go file")
	rootCmd.Flags().StringVar(&packageName, "package", "commands", "Go package name for generated file")

	if err := rootCmd.Execute(); err != nil {
		os.Exit(1)
	}
}
