# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.3.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _falcon_core_dot_gates
else:
    import _falcon_core_dot_gates

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _falcon_core_dot_gates.delete_SwigPyIterator

    def value(self):
        return _falcon_core_dot_gates.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _falcon_core_dot_gates.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _falcon_core_dot_gates.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _falcon_core_dot_gates.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _falcon_core_dot_gates.SwigPyIterator_equal(self, x)

    def copy(self):
        return _falcon_core_dot_gates.SwigPyIterator_copy(self)

    def next(self):
        return _falcon_core_dot_gates.SwigPyIterator_next(self)

    def __next__(self):
        return _falcon_core_dot_gates.SwigPyIterator___next__(self)

    def previous(self):
        return _falcon_core_dot_gates.SwigPyIterator_previous(self)

    def advance(self, n):
        return _falcon_core_dot_gates.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _falcon_core_dot_gates.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _falcon_core_dot_gates.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _falcon_core_dot_gates.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _falcon_core_dot_gates.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _falcon_core_dot_gates.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _falcon_core_dot_gates.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _falcon_core_dot_gates:
_falcon_core_dot_gates.SwigPyIterator_swigregister(SwigPyIterator)
SHARED_PTR_DISOWN = _falcon_core_dot_gates.SHARED_PTR_DISOWN
class Song(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _falcon_core_dot_gates.delete_Song

    def to_json_string(self):
        return _falcon_core_dot_gates.Song_to_json_string(self)

    def to_json_stream(self, os):
        return _falcon_core_dot_gates.Song_to_json_stream(self, os)

    def __eq__(self, other):
        return _falcon_core_dot_gates.Song___eq__(self, other)

    def repr(self):
        return _falcon_core_dot_gates.Song_repr(self)

    def __init__(self):
        _falcon_core_dot_gates.Song_swiginit(self, _falcon_core_dot_gates.new_Song())

# Register Song in _falcon_core_dot_gates:
_falcon_core_dot_gates.Song_swigregister(Song)
class BaseConnection(Song):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __lt__(self, other):
        return _falcon_core_dot_gates.BaseConnection___lt__(self, other)

    def __init__(self, name):
        _falcon_core_dot_gates.BaseConnection_swiginit(self, _falcon_core_dot_gates.new_BaseConnection(name))

    def name(self):
        return _falcon_core_dot_gates.BaseConnection_name(self)
    __swig_destroy__ = _falcon_core_dot_gates.delete_BaseConnection

# Register BaseConnection in _falcon_core_dot_gates:
_falcon_core_dot_gates.BaseConnection_swigregister(BaseConnection)
cvar = _falcon_core_dot_gates.cvar
PI = cvar.PI
ELECTRON_CHARGE = cvar.ELECTRON_CHARGE
CELSIUS_OFFSET = cvar.CELSIUS_OFFSET
FAHRENHEIT_OFFSET = cvar.FAHRENHEIT_OFFSET
SECONDS_PER_MINUTE = cvar.SECONDS_PER_MINUTE
MINUTES_PER_HOUR = cvar.MINUTES_PER_HOUR
UNIT_SCALE_FAHRENHEIT = cvar.UNIT_SCALE_FAHRENHEIT
YOCTO_EXPONENT = cvar.YOCTO_EXPONENT
ZEPTO_EXPONENT = cvar.ZEPTO_EXPONENT
ATTO_EXPONENT = cvar.ATTO_EXPONENT
FEMTO_EXPONENT = cvar.FEMTO_EXPONENT
PICO_EXPONENT = cvar.PICO_EXPONENT
NANO_EXPONENT = cvar.NANO_EXPONENT
MICRO_EXPONENT = cvar.MICRO_EXPONENT
MILLI_EXPONENT = cvar.MILLI_EXPONENT
CENTI_EXPONENT = cvar.CENTI_EXPONENT
UNIT_EXPONENT = cvar.UNIT_EXPONENT
HECTO_EXPONENT = cvar.HECTO_EXPONENT
KILO_EXPONENT = cvar.KILO_EXPONENT
MEGA_EXPONENT = cvar.MEGA_EXPONENT
GIGA_EXPONENT = cvar.GIGA_EXPONENT
TERA_EXPONENT = cvar.TERA_EXPONENT
PETA_EXPONENT = cvar.PETA_EXPONENT
EXA_EXPONENT = cvar.EXA_EXPONENT
ZETTA_EXPONENT = cvar.ZETTA_EXPONENT
YOTTA_EXPONENT = cvar.YOTTA_EXPONENT
YOCTO_SYMBOL = cvar.YOCTO_SYMBOL
ZEPTO_SYMBOL = cvar.ZEPTO_SYMBOL
ATTO_SYMBOL = cvar.ATTO_SYMBOL
FEMTO_SYMBOL = cvar.FEMTO_SYMBOL
PICO_SYMBOL = cvar.PICO_SYMBOL
NANO_SYMBOL = cvar.NANO_SYMBOL
MICRO_SYMBOL = cvar.MICRO_SYMBOL
MILLI_SYMBOL = cvar.MILLI_SYMBOL
CENTI_SYMBOL = cvar.CENTI_SYMBOL
UNIT_SYMBOL = cvar.UNIT_SYMBOL
HECTO_SYMBOL = cvar.HECTO_SYMBOL
KILO_SYMBOL = cvar.KILO_SYMBOL
MEGA_SYMBOL = cvar.MEGA_SYMBOL
GIGA_SYMBOL = cvar.GIGA_SYMBOL
TERA_SYMBOL = cvar.TERA_SYMBOL
PETA_SYMBOL = cvar.PETA_SYMBOL
EXA_SYMBOL = cvar.EXA_SYMBOL
ZETTA_SYMBOL = cvar.ZETTA_SYMBOL
YOTTA_SYMBOL = cvar.YOTTA_SYMBOL
ALL_PREFIXES = cvar.ALL_PREFIXES
DIMENSION_LENGTH = cvar.DIMENSION_LENGTH
DIMENSION_MASS = cvar.DIMENSION_MASS
DIMENSION_TIME = cvar.DIMENSION_TIME
DIMENSION_CURRENT = cvar.DIMENSION_CURRENT
DIMENSION_TEMPERATURE = cvar.DIMENSION_TEMPERATURE
DIMENSION_AMOUNT = cvar.DIMENSION_AMOUNT
DIMENSION_LUMINOSITY = cvar.DIMENSION_LUMINOSITY
ALL_DIMENSIONS = cvar.ALL_DIMENSIONS
DIMENSIONS_DIMENSIONLESS = cvar.DIMENSIONS_DIMENSIONLESS
DIMENSIONS_METER = cvar.DIMENSIONS_METER
DIMENSIONS_KILOGRAM = cvar.DIMENSIONS_KILOGRAM
DIMENSIONS_SECOND = cvar.DIMENSIONS_SECOND
DIMENSIONS_AMPERE = cvar.DIMENSIONS_AMPERE
DIMENSIONS_KELVIN = cvar.DIMENSIONS_KELVIN
DIMENSIONS_MOLE = cvar.DIMENSIONS_MOLE
DIMENSIONS_CANDELA = cvar.DIMENSIONS_CANDELA
DIMENSIONS_HERTZ = cvar.DIMENSIONS_HERTZ
DIMENSIONS_NEWTON = cvar.DIMENSIONS_NEWTON
DIMENSIONS_PASCAL = cvar.DIMENSIONS_PASCAL
DIMENSIONS_JOULE = cvar.DIMENSIONS_JOULE
DIMENSIONS_WATT = cvar.DIMENSIONS_WATT
DIMENSIONS_COULOMB = cvar.DIMENSIONS_COULOMB
DIMENSIONS_VOLT = cvar.DIMENSIONS_VOLT
DIMENSIONS_FARAD = cvar.DIMENSIONS_FARAD
DIMENSIONS_OHM = cvar.DIMENSIONS_OHM
DIMENSIONS_SIEMENS = cvar.DIMENSIONS_SIEMENS
DIMENSIONS_WEBER = cvar.DIMENSIONS_WEBER
DIMENSIONS_TESLA = cvar.DIMENSIONS_TESLA
DIMENSIONS_HENRY = cvar.DIMENSIONS_HENRY
UNIT_SYMBOL_METER = cvar.UNIT_SYMBOL_METER
UNIT_SYMBOL_KILOGRAM = cvar.UNIT_SYMBOL_KILOGRAM
UNIT_SYMBOL_SECOND = cvar.UNIT_SYMBOL_SECOND
UNIT_SYMBOL_AMPERE = cvar.UNIT_SYMBOL_AMPERE
UNIT_SYMBOL_KELVIN = cvar.UNIT_SYMBOL_KELVIN
UNIT_SYMBOL_MOLE = cvar.UNIT_SYMBOL_MOLE
UNIT_SYMBOL_CANDELA = cvar.UNIT_SYMBOL_CANDELA
UNIT_SYMBOL_HERTZ = cvar.UNIT_SYMBOL_HERTZ
UNIT_SYMBOL_NEWTON = cvar.UNIT_SYMBOL_NEWTON
UNIT_SYMBOL_PASCAL = cvar.UNIT_SYMBOL_PASCAL
UNIT_SYMBOL_JOULE = cvar.UNIT_SYMBOL_JOULE
UNIT_SYMBOL_WATT = cvar.UNIT_SYMBOL_WATT
UNIT_SYMBOL_COULOMB = cvar.UNIT_SYMBOL_COULOMB
UNIT_SYMBOL_VOLT = cvar.UNIT_SYMBOL_VOLT
UNIT_SYMBOL_FARAD = cvar.UNIT_SYMBOL_FARAD
UNIT_SYMBOL_OHM = cvar.UNIT_SYMBOL_OHM
UNIT_SYMBOL_SIEMENS = cvar.UNIT_SYMBOL_SIEMENS
UNIT_SYMBOL_WEBER = cvar.UNIT_SYMBOL_WEBER
UNIT_SYMBOL_TESLA = cvar.UNIT_SYMBOL_TESLA
UNIT_SYMBOL_HENRY = cvar.UNIT_SYMBOL_HENRY
UNIT_SYMBOL_MINUTE = cvar.UNIT_SYMBOL_MINUTE
UNIT_SYMBOL_HOUR = cvar.UNIT_SYMBOL_HOUR
UNIT_SYMBOL_ELECTRON_VOLT = cvar.UNIT_SYMBOL_ELECTRON_VOLT
UNIT_SYMBOL_CELSIUS = cvar.UNIT_SYMBOL_CELSIUS
UNIT_SYMBOL_FAHRENHEIT = cvar.UNIT_SYMBOL_FAHRENHEIT
UNIT_SYMBOL_PERCENT = cvar.UNIT_SYMBOL_PERCENT
UNIT_SYMBOL_RADIAN = cvar.UNIT_SYMBOL_RADIAN
UNIT_NAME_METER = cvar.UNIT_NAME_METER
UNIT_NAME_KILOGRAM = cvar.UNIT_NAME_KILOGRAM
UNIT_NAME_SECOND = cvar.UNIT_NAME_SECOND
UNIT_NAME_AMPERE = cvar.UNIT_NAME_AMPERE
UNIT_NAME_KELVIN = cvar.UNIT_NAME_KELVIN
UNIT_NAME_MOLE = cvar.UNIT_NAME_MOLE
UNIT_NAME_CANDELA = cvar.UNIT_NAME_CANDELA
UNIT_NAME_HERTZ = cvar.UNIT_NAME_HERTZ
UNIT_NAME_NEWTON = cvar.UNIT_NAME_NEWTON
UNIT_NAME_PASCAL = cvar.UNIT_NAME_PASCAL
UNIT_NAME_JOULE = cvar.UNIT_NAME_JOULE
UNIT_NAME_WATT = cvar.UNIT_NAME_WATT
UNIT_NAME_COULOMB = cvar.UNIT_NAME_COULOMB
UNIT_NAME_VOLT = cvar.UNIT_NAME_VOLT
UNIT_NAME_FARAD = cvar.UNIT_NAME_FARAD
UNIT_NAME_OHM = cvar.UNIT_NAME_OHM
UNIT_NAME_SIEMENS = cvar.UNIT_NAME_SIEMENS
UNIT_NAME_WEBER = cvar.UNIT_NAME_WEBER
UNIT_NAME_TESLA = cvar.UNIT_NAME_TESLA
UNIT_NAME_HENRY = cvar.UNIT_NAME_HENRY
UNIT_NAME_MINUTE = cvar.UNIT_NAME_MINUTE
UNIT_NAME_HOUR = cvar.UNIT_NAME_HOUR
UNIT_NAME_ELECTRON_VOLT = cvar.UNIT_NAME_ELECTRON_VOLT
UNIT_NAME_CELSIUS = cvar.UNIT_NAME_CELSIUS
UNIT_NAME_FAHRENHEIT = cvar.UNIT_NAME_FAHRENHEIT
UNIT_NAME_DIMENSIONLESS = cvar.UNIT_NAME_DIMENSIONLESS
UNIT_NAME_PERCENT = cvar.UNIT_NAME_PERCENT
UNIT_NAME_RADIAN = cvar.UNIT_NAME_RADIAN
DC_VOLTAGE_SOURCE = cvar.DC_VOLTAGE_SOURCE
AMNMETER = cvar.AMNMETER
MAGNET = cvar.MAGNET
LOCKIN = cvar.LOCKIN
VOLTAGE_SOURCE = cvar.VOLTAGE_SOURCE
CURRENT_SOURCE = cvar.CURRENT_SOURCE
HF_VOLTAGE_SOURCE = cvar.HF_VOLTAGE_SOURCE
DC_CURRENT_SOURCE = cvar.DC_CURRENT_SOURCE
HF_CURRENT_SOURCE = cvar.HF_CURRENT_SOURCE
THERMOMETER = cvar.THERMOMETER
VOLTMETER = cvar.VOLTMETER
FPGA = cvar.FPGA
CLOCK = cvar.CLOCK
DISCRETE = cvar.DISCRETE

class Gate(BaseConnection):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, name):
        _falcon_core_dot_gates.Gate_swiginit(self, _falcon_core_dot_gates.new_Gate(name))
    __swig_destroy__ = _falcon_core_dot_gates.delete_Gate

# Register Gate in _falcon_core_dot_gates:
_falcon_core_dot_gates.Gate_swigregister(Gate)
class DotGate(Gate):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, name):
        _falcon_core_dot_gates.DotGate_swiginit(self, _falcon_core_dot_gates.new_DotGate(name))
    __swig_destroy__ = _falcon_core_dot_gates.delete_DotGate

# Register DotGate in _falcon_core_dot_gates:
_falcon_core_dot_gates.DotGate_swigregister(DotGate)
class BarrierGate(DotGate):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, name):
        _falcon_core_dot_gates.BarrierGate_swiginit(self, _falcon_core_dot_gates.new_BarrierGate(name))
    __swig_destroy__ = _falcon_core_dot_gates.delete_BarrierGate

# Register BarrierGate in _falcon_core_dot_gates:
_falcon_core_dot_gates.BarrierGate_swigregister(BarrierGate)
class ScreeningGate(Gate):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, name):
        _falcon_core_dot_gates.ScreeningGate_swiginit(self, _falcon_core_dot_gates.new_ScreeningGate(name))
    __swig_destroy__ = _falcon_core_dot_gates.delete_ScreeningGate

# Register ScreeningGate in _falcon_core_dot_gates:
_falcon_core_dot_gates.ScreeningGate_swigregister(ScreeningGate)
class ReservoirGate(Gate):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, name):
        _falcon_core_dot_gates.ReservoirGate_swiginit(self, _falcon_core_dot_gates.new_ReservoirGate(name))
    __swig_destroy__ = _falcon_core_dot_gates.delete_ReservoirGate

# Register ReservoirGate in _falcon_core_dot_gates:
_falcon_core_dot_gates.ReservoirGate_swigregister(ReservoirGate)
class PlungerGate(DotGate):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, name):
        _falcon_core_dot_gates.PlungerGate_swiginit(self, _falcon_core_dot_gates.new_PlungerGate(name))
    __swig_destroy__ = _falcon_core_dot_gates.delete_PlungerGate

# Register PlungerGate in _falcon_core_dot_gates:
_falcon_core_dot_gates.PlungerGate_swigregister(PlungerGate)
class Ohmic(BaseConnection):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, name):
        _falcon_core_dot_gates.Ohmic_swiginit(self, _falcon_core_dot_gates.new_Ohmic(name))
    __swig_destroy__ = _falcon_core_dot_gates.delete_Ohmic

# Register Ohmic in _falcon_core_dot_gates:
_falcon_core_dot_gates.Ohmic_swigregister(Ohmic)
class Impedance(Song):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, connection, resistance, capacitance):
        _falcon_core_dot_gates.Impedance_swiginit(self, _falcon_core_dot_gates.new_Impedance(connection, resistance, capacitance))

    def connection(self):
        return _falcon_core_dot_gates.Impedance_connection(self)

    def resistance(self):
        return _falcon_core_dot_gates.Impedance_resistance(self)

    def capacitance(self):
        return _falcon_core_dot_gates.Impedance_capacitance(self)
    __swig_destroy__ = _falcon_core_dot_gates.delete_Impedance

# Register Impedance in _falcon_core_dot_gates:
_falcon_core_dot_gates.Impedance_swigregister(Impedance)
class Prefix(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    @staticmethod
    def get_symbol_to_power_map():
        return _falcon_core_dot_gates.Prefix_get_symbol_to_power_map()

    @staticmethod
    def get_power_to_symbol_map():
        return _falcon_core_dot_gates.Prefix_get_power_to_symbol_map()

    @staticmethod
    def get_symbol(prefix_value):
        return _falcon_core_dot_gates.Prefix_get_symbol(prefix_value)

    @staticmethod
    def get_value(prefix_symbol):
        return _falcon_core_dot_gates.Prefix_get_value(prefix_symbol)

    @staticmethod
    def is_valid(prefix_symbol):
        return _falcon_core_dot_gates.Prefix_is_valid(prefix_symbol)

    @staticmethod
    def prefix_multiplication(first_prefix, second_prefix, scale_factor):
        return _falcon_core_dot_gates.Prefix_prefix_multiplication(first_prefix, second_prefix, scale_factor)

    def __init__(self):
        _falcon_core_dot_gates.Prefix_swiginit(self, _falcon_core_dot_gates.new_Prefix())
    __swig_destroy__ = _falcon_core_dot_gates.delete_Prefix

# Register Prefix in _falcon_core_dot_gates:
_falcon_core_dot_gates.Prefix_swigregister(Prefix)
class Unit(Song):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _falcon_core_dot_gates.Unit_swiginit(self, _falcon_core_dot_gates.new_Unit(*args))

    def prefix(self):
        return _falcon_core_dot_gates.Unit_prefix(self)

    def dimensions(self):
        return _falcon_core_dot_gates.Unit_dimensions(self)

    def scale_factor(self):
        return _falcon_core_dot_gates.Unit_scale_factor(self)

    def offset(self):
        return _falcon_core_dot_gates.Unit_offset(self)

    def __mul__(self, other):
        return _falcon_core_dot_gates.Unit___mul__(self, other)

    def __truediv__(self, *args):
        return _falcon_core_dot_gates.Unit___truediv__(self, *args)
    __div__ = __truediv__



    def __xor__(self, power):
        return _falcon_core_dot_gates.Unit___xor__(self, power)

    def with_prefix(self, prefix):
        return _falcon_core_dot_gates.Unit_with_prefix(self, prefix)

    def convert_value_to(self, value, target_unit):
        return _falcon_core_dot_gates.Unit_convert_value_to(self, value, target_unit)

    def is_compatible_with(self, other):
        return _falcon_core_dot_gates.Unit_is_compatible_with(self, other)
    __swig_destroy__ = _falcon_core_dot_gates.delete_Unit

# Register Unit in _falcon_core_dot_gates:
_falcon_core_dot_gates.Unit_swigregister(Unit)

def get_unit_with_prefix(unit, prefix):
    return _falcon_core_dot_gates.get_unit_with_prefix(unit, prefix)

def get_milli(unit):
    return _falcon_core_dot_gates.get_milli(unit)

def get_micro(unit):
    return _falcon_core_dot_gates.get_micro(unit)

def get_nano(unit):
    return _falcon_core_dot_gates.get_nano(unit)

def get_pico(unit):
    return _falcon_core_dot_gates.get_pico(unit)

def get_kilo(unit):
    return _falcon_core_dot_gates.get_kilo(unit)

def get_mega(unit):
    return _falcon_core_dot_gates.get_mega(unit)

def get_giga(unit):
    return _falcon_core_dot_gates.get_giga(unit)
class SymbolUnit(Song):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, unit):
        _falcon_core_dot_gates.SymbolUnit_swiginit(self, _falcon_core_dot_gates.new_SymbolUnit(unit))

    def unit(self):
        return _falcon_core_dot_gates.SymbolUnit_unit(self)

    def symbol(self):
        return _falcon_core_dot_gates.SymbolUnit_symbol(self)

    def name(self):
        return _falcon_core_dot_gates.SymbolUnit_name(self)

    def __mul__(self, *args):
        return _falcon_core_dot_gates.SymbolUnit___mul__(self, *args)

    def __truediv__(self, *args):
        return _falcon_core_dot_gates.SymbolUnit___truediv__(self, *args)
    __div__ = __truediv__



    def __xor__(self, power):
        return _falcon_core_dot_gates.SymbolUnit___xor__(self, power)

    def with_prefix(self, prefix):
        return _falcon_core_dot_gates.SymbolUnit_with_prefix(self, prefix)

    def convert_value_to(self, value, target_unit):
        return _falcon_core_dot_gates.SymbolUnit_convert_value_to(self, value, target_unit)

    def is_compatible_with(self, other):
        return _falcon_core_dot_gates.SymbolUnit_is_compatible_with(self, other)

    def str(self):
        return _falcon_core_dot_gates.SymbolUnit_str(self)
    __swig_destroy__ = _falcon_core_dot_gates.delete_SymbolUnit

# Register SymbolUnit in _falcon_core_dot_gates:
_falcon_core_dot_gates.SymbolUnit_swigregister(SymbolUnit)
Meter = cvar.Meter
Kilogram = cvar.Kilogram
Second = cvar.Second
Ampere = cvar.Ampere
Kelvin = cvar.Kelvin
Mole = cvar.Mole
Candela = cvar.Candela
Hertz = cvar.Hertz
Newton = cvar.Newton
Pascal = cvar.Pascal
Joule = cvar.Joule
Watt = cvar.Watt
Coulomb = cvar.Coulomb
Volt = cvar.Volt
Farad = cvar.Farad
Ohm = cvar.Ohm
Siemens = cvar.Siemens
Weber = cvar.Weber
Tesla = cvar.Tesla
Henry = cvar.Henry
Minute = cvar.Minute
Hour = cvar.Hour
ElectronVolt = cvar.ElectronVolt
Celsius = cvar.Celsius
Fahrenheit = cvar.Fahrenheit
Dimensionless = cvar.Dimensionless
Percent = cvar.Percent
Radian = cvar.Radian

class Units(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    @staticmethod
    def Meter():
        return _falcon_core_dot_gates.Units_Meter()

    @staticmethod
    def Kilogram():
        return _falcon_core_dot_gates.Units_Kilogram()

    @staticmethod
    def Second():
        return _falcon_core_dot_gates.Units_Second()

    @staticmethod
    def Ampere():
        return _falcon_core_dot_gates.Units_Ampere()

    @staticmethod
    def Kelvin():
        return _falcon_core_dot_gates.Units_Kelvin()

    @staticmethod
    def Mole():
        return _falcon_core_dot_gates.Units_Mole()

    @staticmethod
    def Candela():
        return _falcon_core_dot_gates.Units_Candela()

    @staticmethod
    def Hertz():
        return _falcon_core_dot_gates.Units_Hertz()

    @staticmethod
    def Newton():
        return _falcon_core_dot_gates.Units_Newton()

    @staticmethod
    def Pascal():
        return _falcon_core_dot_gates.Units_Pascal()

    @staticmethod
    def Joule():
        return _falcon_core_dot_gates.Units_Joule()

    @staticmethod
    def Watt():
        return _falcon_core_dot_gates.Units_Watt()

    @staticmethod
    def Coulomb():
        return _falcon_core_dot_gates.Units_Coulomb()

    @staticmethod
    def Volt():
        return _falcon_core_dot_gates.Units_Volt()

    @staticmethod
    def Farad():
        return _falcon_core_dot_gates.Units_Farad()

    @staticmethod
    def Ohm():
        return _falcon_core_dot_gates.Units_Ohm()

    @staticmethod
    def Siemens():
        return _falcon_core_dot_gates.Units_Siemens()

    @staticmethod
    def Weber():
        return _falcon_core_dot_gates.Units_Weber()

    @staticmethod
    def Tesla():
        return _falcon_core_dot_gates.Units_Tesla()

    @staticmethod
    def Henry():
        return _falcon_core_dot_gates.Units_Henry()

    @staticmethod
    def Minute():
        return _falcon_core_dot_gates.Units_Minute()

    @staticmethod
    def Hour():
        return _falcon_core_dot_gates.Units_Hour()

    @staticmethod
    def ElectronVolt():
        return _falcon_core_dot_gates.Units_ElectronVolt()

    @staticmethod
    def Celsius():
        return _falcon_core_dot_gates.Units_Celsius()

    @staticmethod
    def Fahrenheit():
        return _falcon_core_dot_gates.Units_Fahrenheit()

    @staticmethod
    def Dimensionless():
        return _falcon_core_dot_gates.Units_Dimensionless()

    @staticmethod
    def Percent():
        return _falcon_core_dot_gates.Units_Percent()

    @staticmethod
    def Radian():
        return _falcon_core_dot_gates.Units_Radian()

    @staticmethod
    def MilliMeter():
        return _falcon_core_dot_gates.Units_MilliMeter()

    @staticmethod
    def KiloMeter():
        return _falcon_core_dot_gates.Units_KiloMeter()

    @staticmethod
    def MilliVolt():
        return _falcon_core_dot_gates.Units_MilliVolt()

    @staticmethod
    def KiloVolt():
        return _falcon_core_dot_gates.Units_KiloVolt()

    @staticmethod
    def MilliAmpere():
        return _falcon_core_dot_gates.Units_MilliAmpere()

    @staticmethod
    def MicroAmpere():
        return _falcon_core_dot_gates.Units_MicroAmpere()

    @staticmethod
    def NanoAmpere():
        return _falcon_core_dot_gates.Units_NanoAmpere()

    @staticmethod
    def PicoAmpere():
        return _falcon_core_dot_gates.Units_PicoAmpere()

    @staticmethod
    def MilliSecond():
        return _falcon_core_dot_gates.Units_MilliSecond()

    @staticmethod
    def MicroSecond():
        return _falcon_core_dot_gates.Units_MicroSecond()

    @staticmethod
    def NanoSecond():
        return _falcon_core_dot_gates.Units_NanoSecond()

    @staticmethod
    def PicoSecond():
        return _falcon_core_dot_gates.Units_PicoSecond()

    @staticmethod
    def MilliOhm():
        return _falcon_core_dot_gates.Units_MilliOhm()

    @staticmethod
    def KiloOhm():
        return _falcon_core_dot_gates.Units_KiloOhm()

    @staticmethod
    def MegaOhm():
        return _falcon_core_dot_gates.Units_MegaOhm()

    @staticmethod
    def MilliHertz():
        return _falcon_core_dot_gates.Units_MilliHertz()

    @staticmethod
    def KiloHertz():
        return _falcon_core_dot_gates.Units_KiloHertz()

    @staticmethod
    def MegaHertz():
        return _falcon_core_dot_gates.Units_MegaHertz()

    @staticmethod
    def GigaHertz():
        return _falcon_core_dot_gates.Units_GigaHertz()

    @staticmethod
    def MetersPerSecond():
        return _falcon_core_dot_gates.Units_MetersPerSecond()

    @staticmethod
    def MetersPerSecondSquared():
        return _falcon_core_dot_gates.Units_MetersPerSecondSquared()

    @staticmethod
    def NewtonMeter():
        return _falcon_core_dot_gates.Units_NewtonMeter()

    @staticmethod
    def NewtonPerMeter():
        return _falcon_core_dot_gates.Units_NewtonPerMeter()

    @staticmethod
    def VoltsPerMeter():
        return _falcon_core_dot_gates.Units_VoltsPerMeter()

    @staticmethod
    def VoltsPerSecond():
        return _falcon_core_dot_gates.Units_VoltsPerSecond()

    @staticmethod
    def AmperesPerMeter():
        return _falcon_core_dot_gates.Units_AmperesPerMeter()

    @staticmethod
    def VoltsPerAmpere():
        return _falcon_core_dot_gates.Units_VoltsPerAmpere()

    @staticmethod
    def WattsPerMeterKelvin():
        return _falcon_core_dot_gates.Units_WattsPerMeterKelvin()

    def __init__(self):
        _falcon_core_dot_gates.Units_swiginit(self, _falcon_core_dot_gates.new_Units())
    __swig_destroy__ = _falcon_core_dot_gates.delete_Units

# Register Units in _falcon_core_dot_gates:
_falcon_core_dot_gates.Units_swigregister(Units)
class Quantity(Song):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, value, unit):
        _falcon_core_dot_gates.Quantity_swiginit(self, _falcon_core_dot_gates.new_Quantity(value, unit))

    def value(self):
        return _falcon_core_dot_gates.Quantity_value(self)

    def unit(self):
        return _falcon_core_dot_gates.Quantity_unit(self)

    def convert_to(self, target_unit):
        return _falcon_core_dot_gates.Quantity_convert_to(self, target_unit)

    def __mul__(self, *args):
        return _falcon_core_dot_gates.Quantity___mul__(self, *args)

    def __truediv__(self, *args):
        return _falcon_core_dot_gates.Quantity___truediv__(self, *args)
    __div__ = __truediv__



    def __xor__(self, other):
        return _falcon_core_dot_gates.Quantity___xor__(self, other)

    def __add__(self, *args):
        return _falcon_core_dot_gates.Quantity___add__(self, *args)

    def __neg__(self):
        return _falcon_core_dot_gates.Quantity___neg__(self)

    def __sub__(self, *args):
        return _falcon_core_dot_gates.Quantity___sub__(self, *args)

    def abs(self):
        return _falcon_core_dot_gates.Quantity_abs(self)
    __swig_destroy__ = _falcon_core_dot_gates.delete_Quantity

# Register Quantity in _falcon_core_dot_gates:
_falcon_core_dot_gates.Quantity_swigregister(Quantity)
class falcon_core__math__arrays__BaseArray_double_(Song):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _falcon_core_dot_gates.falcon_core__math__arrays__BaseArray_double__swiginit(self, _falcon_core_dot_gates.new_falcon_core__math__arrays__BaseArray_double_(*args))

    def data(self, *args):
        return _falcon_core_dot_gates.falcon_core__math__arrays__BaseArray_double__data(self, *args)

    def is_1d(self):
        return _falcon_core_dot_gates.falcon_core__math__arrays__BaseArray_double__is_1d(self)
    __swig_destroy__ = _falcon_core_dot_gates.delete_falcon_core__math__arrays__BaseArray_double_

# Register falcon_core__math__arrays__BaseArray_double_ in _falcon_core_dot_gates:
_falcon_core_dot_gates.falcon_core__math__arrays__BaseArray_double__swigregister(falcon_core__math__arrays__BaseArray_double_)
class falcon_core__math__arrays__ControlArray_double_(falcon_core__math__arrays__BaseArray_double_):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _falcon_core_dot_gates.falcon_core__math__arrays__ControlArray_double__swiginit(self, _falcon_core_dot_gates.new_falcon_core__math__arrays__ControlArray_double_(*args))
    __swig_destroy__ = _falcon_core_dot_gates.delete_falcon_core__math__arrays__ControlArray_double_

# Register falcon_core__math__arrays__ControlArray_double_ in _falcon_core_dot_gates:
_falcon_core_dot_gates.falcon_core__math__arrays__ControlArray_double__swigregister(falcon_core__math__arrays__ControlArray_double_)
class ControlArray1D(falcon_core__math__arrays__ControlArray_double_):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, data):
        _falcon_core_dot_gates.ControlArray1D_swiginit(self, _falcon_core_dot_gates.new_ControlArray1D(data))
    __swig_destroy__ = _falcon_core_dot_gates.delete_ControlArray1D

# Register ControlArray1D in _falcon_core_dot_gates:
_falcon_core_dot_gates.ControlArray1D_swigregister(ControlArray1D)
class IncreasingAlignment(Song):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _falcon_core_dot_gates.IncreasingAlignment_swiginit(self, _falcon_core_dot_gates.new_IncreasingAlignment())
    __swig_destroy__ = _falcon_core_dot_gates.delete_IncreasingAlignment

# Register IncreasingAlignment in _falcon_core_dot_gates:
_falcon_core_dot_gates.IncreasingAlignment_swigregister(IncreasingAlignment)

