# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.3.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _falcon_core_reservoir_gate
else:
    import _falcon_core_reservoir_gate

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class Song(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _falcon_core_reservoir_gate.delete_Song

    def to_json_string(self):
        return _falcon_core_reservoir_gate.Song_to_json_string(self)

    def to_json_stream(self, os):
        return _falcon_core_reservoir_gate.Song_to_json_stream(self, os)

    def __eq__(self, other):
        return _falcon_core_reservoir_gate.Song___eq__(self, other)

    def repr(self):
        return _falcon_core_reservoir_gate.Song_repr(self)

    def __init__(self):
        _falcon_core_reservoir_gate.Song_swiginit(self, _falcon_core_reservoir_gate.new_Song())

# Register Song in _falcon_core_reservoir_gate:
_falcon_core_reservoir_gate.Song_swigregister(Song)
class BaseConnection(Song):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __lt__(self, other):
        return _falcon_core_reservoir_gate.BaseConnection___lt__(self, other)

    def __init__(self, name):
        _falcon_core_reservoir_gate.BaseConnection_swiginit(self, _falcon_core_reservoir_gate.new_BaseConnection(name))

    def name(self):
        return _falcon_core_reservoir_gate.BaseConnection_name(self)
    __swig_destroy__ = _falcon_core_reservoir_gate.delete_BaseConnection

# Register BaseConnection in _falcon_core_reservoir_gate:
_falcon_core_reservoir_gate.BaseConnection_swigregister(BaseConnection)
class Gate(BaseConnection):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, name):
        _falcon_core_reservoir_gate.Gate_swiginit(self, _falcon_core_reservoir_gate.new_Gate(name))
    __swig_destroy__ = _falcon_core_reservoir_gate.delete_Gate

# Register Gate in _falcon_core_reservoir_gate:
_falcon_core_reservoir_gate.Gate_swigregister(Gate)
class DotGate(Gate):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, name):
        _falcon_core_reservoir_gate.DotGate_swiginit(self, _falcon_core_reservoir_gate.new_DotGate(name))
    __swig_destroy__ = _falcon_core_reservoir_gate.delete_DotGate

# Register DotGate in _falcon_core_reservoir_gate:
_falcon_core_reservoir_gate.DotGate_swigregister(DotGate)
class BarrierGate(DotGate):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, name):
        _falcon_core_reservoir_gate.BarrierGate_swiginit(self, _falcon_core_reservoir_gate.new_BarrierGate(name))
    __swig_destroy__ = _falcon_core_reservoir_gate.delete_BarrierGate

# Register BarrierGate in _falcon_core_reservoir_gate:
_falcon_core_reservoir_gate.BarrierGate_swigregister(BarrierGate)
class ScreeningGate(Gate):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, name):
        _falcon_core_reservoir_gate.ScreeningGate_swiginit(self, _falcon_core_reservoir_gate.new_ScreeningGate(name))
    __swig_destroy__ = _falcon_core_reservoir_gate.delete_ScreeningGate

# Register ScreeningGate in _falcon_core_reservoir_gate:
_falcon_core_reservoir_gate.ScreeningGate_swigregister(ScreeningGate)
class ReservoirGate(Gate):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, name):
        _falcon_core_reservoir_gate.ReservoirGate_swiginit(self, _falcon_core_reservoir_gate.new_ReservoirGate(name))

    @staticmethod
    def from_json_string(json):
        return _falcon_core_reservoir_gate.ReservoirGate_from_json_string(json)

    @staticmethod
    def from_json_stream(_is):
        return _falcon_core_reservoir_gate.ReservoirGate_from_json_stream(_is)
    __swig_destroy__ = _falcon_core_reservoir_gate.delete_ReservoirGate

# Register ReservoirGate in _falcon_core_reservoir_gate:
_falcon_core_reservoir_gate.ReservoirGate_swigregister(ReservoirGate)
class PlungerGate(DotGate):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, name):
        _falcon_core_reservoir_gate.PlungerGate_swiginit(self, _falcon_core_reservoir_gate.new_PlungerGate(name))
    __swig_destroy__ = _falcon_core_reservoir_gate.delete_PlungerGate

# Register PlungerGate in _falcon_core_reservoir_gate:
_falcon_core_reservoir_gate.PlungerGate_swigregister(PlungerGate)
class Ohmic(BaseConnection):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, name):
        _falcon_core_reservoir_gate.Ohmic_swiginit(self, _falcon_core_reservoir_gate.new_Ohmic(name))
    __swig_destroy__ = _falcon_core_reservoir_gate.delete_Ohmic

# Register Ohmic in _falcon_core_reservoir_gate:
_falcon_core_reservoir_gate.Ohmic_swigregister(Ohmic)
class Impedance(Song):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, connection, resistance, capacitance):
        _falcon_core_reservoir_gate.Impedance_swiginit(self, _falcon_core_reservoir_gate.new_Impedance(connection, resistance, capacitance))

    def connection(self):
        return _falcon_core_reservoir_gate.Impedance_connection(self)

    def resistance(self):
        return _falcon_core_reservoir_gate.Impedance_resistance(self)

    def capacitance(self):
        return _falcon_core_reservoir_gate.Impedance_capacitance(self)
    __swig_destroy__ = _falcon_core_reservoir_gate.delete_Impedance

# Register Impedance in _falcon_core_reservoir_gate:
_falcon_core_reservoir_gate.Impedance_swigregister(Impedance)

