"""The constants used throughout Falcon."""

from enum import Enum
from math import pi

PI = pi
ELECTRON_CHARGE = 1.602176634e-19
CELSIUS_OFFSET = 273.15
FAHRENHEIT_OFFSET = 459.67
SECONDS_PER_MINUTE = 60
MINUTES_PER_HOUR = 60
JSONABLE_ATTRIBUTE_INDICATOR = "_"

JSONABLE_CLASS_METADATA = "__class__"
JSONABLE_MODULE_METADATA = "__module__"
JSONABLE_KEY = "__jsonable_key__"
JSONABLE_BLOB = "__binary_blob__"
JSONABLE_TYPE_VAR = "__jsonable_type__"
JSONABLE_FUNCTION = "__jsonable_function__"  # Marker for serialized functions
JSONABLE_FUNCTION_DILL = "__function_dill__"  # Marker for dill-serialized functions
JSONABLE_METADATA = set([JSONABLE_CLASS_METADATA, JSONABLE_MODULE_METADATA])

# SI prefix values
YOCTO_EXPONENT = -24
ZEPTO_EXPONENT = -21
ATTO_EXPONENT = -18
FEMTO_EXPONENT = -15
PICO_EXPONENT = -12
NANO_EXPONENT = -9
MICRO_EXPONENT = -6
MILLI_EXPONENT = -3
CENTI_EXPONENT = -2
DECI_EXPONENT = -1
UNIT_EXPONENT = 0  # No prefix
DECA_EXPONENT = 1
HECTO_EXPONENT = 2
KILO_EXPONENT = 3
MEGA_EXPONENT = 6
GIGA_EXPONENT = 9
TERA_EXPONENT = 12
PETA_EXPONENT = 15
EXA_EXPONENT = 18
ZETTA_EXPONENT = 21
YOTTA_EXPONENT = 24

# SI prefix symbols
YOCTO_SYMBOL = "y"
ZEPTO_SYMBOL = "z"
ATTO_SYMBOL = "a"
FEMTO_SYMBOL = "f"
PICO_SYMBOL = "p"
NANO_SYMBOL = "n"
MICRO_SYMBOL = "μ"
MILLI_SYMBOL = "m"
CENTI_SYMBOL = "c"
DECI_SYMBOL = "d"
UNIT_SYMBOL = ""  # No prefix
DECA_SYMBOL = "da"
HECTO_SYMBOL = "h"
KILO_SYMBOL = "k"
MEGA_SYMBOL = "M"
GIGA_SYMBOL = "G"
TERA_SYMBOL = "T"
PETA_SYMBOL = "P"
EXA_SYMBOL = "E"
ZETTA_SYMBOL = "Z"
YOTTA_SYMBOL = "Y"

ALL_PREFIXES = {
    YOCTO_SYMBOL,
    ZEPTO_SYMBOL,
    ATTO_SYMBOL,
    FEMTO_SYMBOL,
    PICO_SYMBOL,
    NANO_SYMBOL,
    MICRO_SYMBOL,
    MILLI_SYMBOL,
    CENTI_SYMBOL,
    DECI_SYMBOL,
    UNIT_SYMBOL,
    DECA_SYMBOL,
    HECTO_SYMBOL,
    KILO_SYMBOL,
    MEGA_SYMBOL,
    GIGA_SYMBOL,
    TERA_SYMBOL,
    PETA_SYMBOL,
    EXA_SYMBOL,
    ZETTA_SYMBOL,
    YOTTA_SYMBOL,
}

# Physical dimension constants
DIMENSION_LENGTH = "LENGTH"
DIMENSION_MASS = "MASS"
DIMENSION_TIME = "TIME"
DIMENSION_CURRENT = "CURRENT"
DIMENSION_TEMPERATURE = "TEMPERATURE"
DIMENSION_AMOUNT = "AMOUNT"
DIMENSION_LUMINOSITY = "LUMINOSITY"

# Set of all valid dimensions
ALL_DIMENSIONS = {
    DIMENSION_LENGTH,
    DIMENSION_MASS,
    DIMENSION_TIME,
    DIMENSION_CURRENT,
    DIMENSION_TEMPERATURE,
    DIMENSION_AMOUNT,
    DIMENSION_LUMINOSITY,
}

# Unit dimensions dictionaries - centralize the dimensional relationships
DIMENSIONS_DIMENSIONLESS: dict[str, int] = {}
DIMENSIONS_METER = {DIMENSION_LENGTH: 1}
DIMENSIONS_KILOGRAM = {DIMENSION_MASS: 1}
DIMENSIONS_SECOND = {DIMENSION_TIME: 1}
DIMENSIONS_AMPERE = {DIMENSION_CURRENT: 1}
DIMENSIONS_KELVIN = {DIMENSION_TEMPERATURE: 1}
DIMENSIONS_MOLE = {DIMENSION_AMOUNT: 1}
DIMENSIONS_CANDELA = {DIMENSION_LUMINOSITY: 1}
DIMENSIONS_HERTZ = {DIMENSION_TIME: -1}
DIMENSIONS_NEWTON = {DIMENSION_MASS: 1, DIMENSION_LENGTH: 1, DIMENSION_TIME: -2}
DIMENSIONS_PASCAL = {DIMENSION_MASS: 1, DIMENSION_LENGTH: -1, DIMENSION_TIME: -2}
DIMENSIONS_JOULE = {DIMENSION_MASS: 1, DIMENSION_LENGTH: 2, DIMENSION_TIME: -2}
DIMENSIONS_WATT = {DIMENSION_MASS: 1, DIMENSION_LENGTH: 2, DIMENSION_TIME: -3}
DIMENSIONS_COULOMB = {DIMENSION_TIME: 1, DIMENSION_CURRENT: 1}
DIMENSIONS_VOLT = {
    DIMENSION_MASS: 1,
    DIMENSION_LENGTH: 2,
    DIMENSION_TIME: -3,
    DIMENSION_CURRENT: -1,
}
DIMENSIONS_FARAD = {
    DIMENSION_MASS: -1,
    DIMENSION_LENGTH: -2,
    DIMENSION_TIME: 4,
    DIMENSION_CURRENT: 2,
}
DIMENSIONS_OHM = {
    DIMENSION_MASS: 1,
    DIMENSION_LENGTH: 2,
    DIMENSION_TIME: -3,
    DIMENSION_CURRENT: -2,
}
DIMENSIONS_SIEMENS = {
    DIMENSION_MASS: -1,
    DIMENSION_LENGTH: -2,
    DIMENSION_TIME: 3,
    DIMENSION_CURRENT: 2,
}
DIMENSIONS_WEBER = {
    DIMENSION_MASS: 1,
    DIMENSION_LENGTH: 2,
    DIMENSION_TIME: -2,
    DIMENSION_CURRENT: -1,
}
DIMENSIONS_TESLA = {DIMENSION_MASS: 1, DIMENSION_TIME: -2, DIMENSION_CURRENT: -1}
DIMENSIONS_HENRY = {
    DIMENSION_MASS: 1,
    DIMENSION_LENGTH: 2,
    DIMENSION_TIME: -2,
    DIMENSION_CURRENT: -2,
}

# Unit symbols
UNIT_SYMBOL_METER = "m"
UNIT_SYMBOL_KILOGRAM = "kg"
UNIT_SYMBOL_SECOND = "s"
UNIT_SYMBOL_AMPERE = "A"
UNIT_SYMBOL_KELVIN = "K"
UNIT_SYMBOL_MOLE = "mol"
UNIT_SYMBOL_CANDELA = "cd"
UNIT_SYMBOL_HERTZ = "Hz"
UNIT_SYMBOL_NEWTON = "N"
UNIT_SYMBOL_PASCAL = "Pa"
UNIT_SYMBOL_JOULE = "J"
UNIT_SYMBOL_WATT = "W"
UNIT_SYMBOL_COULOMB = "C"
UNIT_SYMBOL_VOLT = "V"
UNIT_SYMBOL_FARAD = "F"
UNIT_SYMBOL_OHM = "Ω"
UNIT_SYMBOL_SIEMENS = "S"
UNIT_SYMBOL_WEBER = "Wb"
UNIT_SYMBOL_TESLA = "T"
UNIT_SYMBOL_HENRY = "H"
UNIT_SYMBOL_MINUTE = "min"
UNIT_SYMBOL_HOUR = "h"
UNIT_SYMBOL_ELECTRON_VOLT = "eV"
UNIT_SYMBOL_CELSIUS = "°C"
UNIT_SYMBOL_FAHRENHEIT = "°F"
UNIT_SYMBOL_PERCENT = "%"
UNIT_SYMBOL_RADIAN = "rad"

# Unit names
UNIT_NAME_METER = "meter"
UNIT_NAME_KILOGRAM = "kilogram"
UNIT_NAME_SECOND = "second"
UNIT_NAME_AMPERE = "ampere"
UNIT_NAME_KELVIN = "kelvin"
UNIT_NAME_MOLE = "mole"
UNIT_NAME_CANDELA = "candela"
UNIT_NAME_HERTZ = "hertz"
UNIT_NAME_NEWTON = "newton"
UNIT_NAME_PASCAL = "pascal"
UNIT_NAME_JOULE = "joule"
UNIT_NAME_WATT = "watt"
UNIT_NAME_COULOMB = "coulomb"
UNIT_NAME_VOLT = "volt"
UNIT_NAME_FARAD = "farad"
UNIT_NAME_OHM = "ohm"
UNIT_NAME_SIEMENS = "siemens"
UNIT_NAME_WEBER = "weber"
UNIT_NAME_TESLA = "tesla"
UNIT_NAME_HENRY = "henry"
UNIT_NAME_MINUTE = "minute"
UNIT_NAME_HOUR = "hour"
UNIT_NAME_ELECTRON_VOLT = "electron-volt"
UNIT_NAME_CELSIUS = "celsius"
UNIT_NAME_FAHRENHEIT = "fahrenheit"
UNIT_NAME_DIMENSIONLESS = "dimensionless"
UNIT_NAME_PERCENT = "percent"
UNIT_NAME_RADIAN = "radian"

UNIT_SCALE_FAHRENHEIT = 5 / 9


class INSTRUMENT_TYPES(Enum):
    """Instrument types."""

    DC_VOLTAGE_SOURCE = "dc_voltage_source"
    AMNMETER = "amnmeter"
    MAGNET = "magnet"
    LOCKIN = "lockin"
    VOLTAGE_SOURCE = "voltage_source"
    CURRENT_SOURCE = "current_source"
    HF_VOLTAGE_SOURCE = "hf_voltage_source"
    DC_CURRENT_SOURCE = "dc_current_source"
    HF_CURRENT_SOURCE = "hf_current_source"
    THERMOMETER = "thermometer"
    VOLTMETER = "voltmeter"
    FPGA = "fpga"
    CLOCK = "clock"
