# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.3.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _falcon_core
else:
    import _falcon_core

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import weakref


import sys
import importlib.util

# This code runs when the falcon_core module is imported.
# It creates the desired submodule structure in memory.
_pkg_name = __name__

# Create falcon_core.generic
_generic_spec = importlib.util.spec_from_loader(f'{_pkg_name}.generic', loader=None)
generic = importlib.util.module_from_spec(_generic_spec)
sys.modules[generic.__name__] = generic
setattr(sys.modules[_pkg_name], 'generic', generic)

# Create falcon_core.communications
_comm_spec = importlib.util.spec_from_loader(f'{_pkg_name}.communications', loader=None)
communications = importlib.util.module_from_spec(_comm_spec)
sys.modules[communications.__name__] = communications
setattr(sys.modules[_pkg_name], 'communications', communications)

# Create falcon_core.physics
_physics_spec = importlib.util.spec_from_loader(f'{_pkg_name}.physics', loader=None)
physics = importlib.util.module_from_spec(_physics_spec)
sys.modules[physics.__name__] = physics
setattr(sys.modules[_pkg_name], 'physics', physics)

# Create falcon_core.physics.units
_units_spec = importlib.util.spec_from_loader(f'{_pkg_name}.physics.units', loader=None)
physics.units = importlib.util.module_from_spec(_units_spec)
sys.modules[physics.units.__name__] = physics.units

# Create falcon_core.math
_math_spec = importlib.util.spec_from_loader(f'{_pkg_name}.math', loader=None)
math = importlib.util.module_from_spec(_math_spec)
sys.modules[math.__name__] = math
setattr(sys.modules[_pkg_name], 'math', math)

# Create falcon_core.math.domains
_domains_spec = importlib.util.spec_from_loader(f'{_pkg_name}.math.domains', loader=None)
math.domains = importlib.util.module_from_spec(_domains_spec)
sys.modules[math.domains.__name__] = math.domains

# Create falcon_core.math.arrays
_arrays_spec = importlib.util.spec_from_loader(f'{_pkg_name}.math.arrays', loader=None)
math.arrays = importlib.util.module_from_spec(_arrays_spec)
sys.modules[math.arrays.__name__] = math.arrays

# Create falcon_core.math.axes
_axes_spec = importlib.util.spec_from_loader(f'{_pkg_name}.math.axes', loader=None)
math.axes = importlib.util.module_from_spec(_axes_spec)
sys.modules[math.axes.__name__] = math.axes

# Create falcon_core.physics.device_structures
_devices_spec = importlib.util.spec_from_loader(f'{_pkg_name}.physics.device_structures', loader=None)
physics.device_structures = importlib.util.module_from_spec(_devices_spec)
sys.modules[physics.device_structures.__name__] = physics.device_structures

# Create falcon_core.physics.config
_config_spec = importlib.util.spec_from_loader(f'{_pkg_name}.physics.config', loader=None)
physics.config = importlib.util.module_from_spec(_config_spec)
sys.modules[physics.config.__name__] = physics.config

# Create falcon_core.physics.config.core
_config_core_spec = importlib.util.spec_from_loader(f'{_pkg_name}.physics.config.core', loader=None)
physics.config.core = importlib.util.module_from_spec(_config_core_spec)
sys.modules[physics.config.core.__name__] = physics.config.core

# Create falcon_core.instrument_interfaces
_instruments_spec = importlib.util.spec_from_loader(f'{_pkg_name}.instrument_interfaces', loader=None)
instrument_interfaces = importlib.util.module_from_spec(_instruments_spec)
sys.modules[instrument_interfaces.__name__] = instrument_interfaces
setattr(sys.modules[_pkg_name], 'instrument_interfaces', instrument_interfaces)

# Create falcon_core.instrument_interfaces.names
_instruments_names_spec = importlib.util.spec_from_loader(f'{_pkg_name}.instrument_interfaces.names', loader=None)
instrument_interfaces.names = importlib.util.module_from_spec(_instruments_names_spec)
sys.modules[instrument_interfaces.names.__name__] = instrument_interfaces.names

# Create falcon_core.autotuner_interfaces
_autotuner_spec = importlib.util.spec_from_loader(f'{_pkg_name}.autotuner_interfaces', loader=None)
autotuner_interfaces = importlib.util.module_from_spec(_autotuner_spec)
sys.modules[autotuner_interfaces.__name__] = autotuner_interfaces
setattr(sys.modules[_pkg_name], 'autotuner_interfaces', autotuner_interfaces)

# Create falcon_core.autotuner_interfaces.contexts
_contexts_spec = importlib.util.spec_from_loader(f'{_pkg_name}.autotuner_interfaces.contexts', loader=None)
autotuner_interfaces.contexts = importlib.util.module_from_spec(_contexts_spec)
sys.modules[autotuner_interfaces.contexts.__name__] = autotuner_interfaces.contexts

# Create falcon_core.autotuner_interfaces.interpretations
_interpretations_spec = importlib.util.spec_from_loader(f'{_pkg_name}.autotuner_interfaces.interpretations', loader=None)
autotuner_interfaces.interpretations = importlib.util.module_from_spec(_interpretations_spec)
sys.modules[autotuner_interfaces.interpretations.__name__] = autotuner_interfaces.interpretations

# Create falcon_core.math.functions
_functions_spec = importlib.util.spec_from_loader(f'{_pkg_name}.math.functions', loader=None)
math.functions = importlib.util.module_from_spec(_functions_spec)
sys.modules[math.functions.__name__] = math.functions

# Create falcon_core.physics.transforms
_transforms_spec = importlib.util.spec_from_loader(f'{_pkg_name}.physics.transforms', loader=None)
physics.transforms = importlib.util.module_from_spec(_transforms_spec)
sys.modules[physics.transforms.__name__] = physics.transforms

# Create falcon_core.math.discretizers
_discretizers_spec = importlib.util.spec_from_loader(f'{_pkg_name}.math.discretizers', loader=None)
math.discretizers = importlib.util.module_from_spec(_discretizers_spec)
sys.modules[math.discretizers.__name__] = math.discretizers

# Create falcon_core.math.waveform
_waveform_spec = importlib.util.spec_from_loader(f'{_pkg_name}.math.waveform', loader=None)
math.waveform = importlib.util.module_from_spec(_waveform_spec)
sys.modules[math.waveform.__name__] = math.waveform

# Create falcon_core.math.labelled_arrays
_labelled_arrays_spec = importlib.util.spec_from_loader(f'{_pkg_name}.math.labelled_arrays', loader=None)
math.labelled_arrays = importlib.util.module_from_spec(_labelled_arrays_spec)
sys.modules[math.labelled_arrays.__name__] = math.labelled_arrays

SHARED_PTR_DISOWN = _falcon_core.SHARED_PTR_DISOWN
class Jsonable(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _falcon_core.delete_Jsonable

    def to_json(self):
        return _falcon_core.Jsonable_to_json(self)

    def hash(self):
        return _falcon_core.Jsonable_hash(self)

    def to_json_string(self):
        return _falcon_core.Jsonable_to_json_string(self)

    def __str__(self):
        return _falcon_core.Jsonable___str__(self)

    def __hash__(self):
        return _falcon_core.Jsonable___hash__(self)

# Register Jsonable in _falcon_core:
_falcon_core.Jsonable_swigregister(Jsonable)
class Time(Jsonable):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _falcon_core.Time_swiginit(self, _falcon_core.new_Time())

    def time(self):
        return _falcon_core.Time_time(self)

    def to_json(self):
        return _falcon_core.Time_to_json(self)

    def hash(self):
        return _falcon_core.Time_hash(self)
    __swig_destroy__ = _falcon_core.delete_Time

# Register Time in _falcon_core:
_falcon_core.Time_swigregister(Time)
Sign_POSITIVE = _falcon_core.Sign_POSITIVE
Sign_NEGATIVE = _falcon_core.Sign_NEGATIVE
BaseDimension_LENGTH = _falcon_core.BaseDimension_LENGTH
BaseDimension_MASS = _falcon_core.BaseDimension_MASS
BaseDimension_TIME = _falcon_core.BaseDimension_TIME
BaseDimension_CURRENT = _falcon_core.BaseDimension_CURRENT
BaseDimension_TEMPERATURE = _falcon_core.BaseDimension_TEMPERATURE
BaseDimension_LUMINOUS_INTENSITY = _falcon_core.BaseDimension_LUMINOUS_INTENSITY
BaseDimension_AMOUNT_OF_SUBSTANCE = _falcon_core.BaseDimension_AMOUNT_OF_SUBSTANCE
class Dimension(Jsonable):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, dimensions):
        _falcon_core.Dimension_swiginit(self, _falcon_core.new_Dimension(dimensions))

    def is_dimensionless(self):
        return _falcon_core.Dimension_is_dimensionless(self)

    def to_string(self):
        return _falcon_core.Dimension_to_string(self)

    def to_json(self):
        return _falcon_core.Dimension_to_json(self)

    def hash(self):
        return _falcon_core.Dimension_hash(self)

    def __eq__(self, other):
        return _falcon_core.Dimension___eq__(self, other)

    def __ne__(self, other):
        return _falcon_core.Dimension___ne__(self, other)

    def get_dimensions(self):
        return _falcon_core.Dimension_get_dimensions(self)
    __swig_destroy__ = _falcon_core.delete_Dimension

# Register Dimension in _falcon_core:
_falcon_core.Dimension_swigregister(Dimension)
class Prefix(Jsonable):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, symbol, factor):
        _falcon_core.Prefix_swiginit(self, _falcon_core.new_Prefix(symbol, factor))

    def symbol(self):
        return _falcon_core.Prefix_symbol(self)

    def factor(self):
        return _falcon_core.Prefix_factor(self)

    def to_json(self):
        return _falcon_core.Prefix_to_json(self)

    def hash(self):
        return _falcon_core.Prefix_hash(self)
    __swig_destroy__ = _falcon_core.delete_Prefix

# Register Prefix in _falcon_core:
_falcon_core.Prefix_swigregister(Prefix)
class Unit(Jsonable):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, factor, dimensions):
        _falcon_core.Unit_swiginit(self, _falcon_core.new_Unit(factor, dimensions))

    def get_factor(self):
        return _falcon_core.Unit_get_factor(self)

    def dimensions(self):
        return _falcon_core.Unit_dimensions(self)

    def get_conversion_factor(self, target_unit):
        return _falcon_core.Unit_get_conversion_factor(self, target_unit)

    def to_json(self):
        return _falcon_core.Unit_to_json(self)

    def hash(self):
        return _falcon_core.Unit_hash(self)

    def __mul__(self, other):
        return _falcon_core.Unit___mul__(self, other)

    def __truediv__(self, *args):
        return _falcon_core.Unit___truediv__(self, *args)
    __div__ = __truediv__


    __swig_destroy__ = _falcon_core.delete_Unit

# Register Unit in _falcon_core:
_falcon_core.Unit_swigregister(Unit)
class SymbolUnit(Jsonable):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, unit, symbol):
        _falcon_core.SymbolUnit_swiginit(self, _falcon_core.new_SymbolUnit(unit, symbol))

    def symbol(self):
        return _falcon_core.SymbolUnit_symbol(self)

    def unit(self):
        return _falcon_core.SymbolUnit_unit(self)

    def to_json(self):
        return _falcon_core.SymbolUnit_to_json(self)

    def hash(self):
        return _falcon_core.SymbolUnit_hash(self)
    __swig_destroy__ = _falcon_core.delete_SymbolUnit

# Register SymbolUnit in _falcon_core:
_falcon_core.SymbolUnit_swigregister(SymbolUnit)
class Units(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    @staticmethod
    def V():
        return _falcon_core.Units_V()

    @staticmethod
    def A():
        return _falcon_core.Units_A()

    @staticmethod
    def s():
        return _falcon_core.Units_s()

    @staticmethod
    def Hz():
        return _falcon_core.Units_Hz()

    @staticmethod
    def dimensionless():
        return _falcon_core.Units_dimensionless()
    __swig_destroy__ = _falcon_core.delete_Units

# Register Units in _falcon_core:
_falcon_core.Units_swigregister(Units)
class Domain(Jsonable):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, min_val, max_val):
        _falcon_core.Domain_swiginit(self, _falcon_core.new_Domain(min_val, max_val))

    def min(self):
        return _falcon_core.Domain_min(self)

    def max(self):
        return _falcon_core.Domain_max(self)

    def range(self):
        return _falcon_core.Domain_range(self)

    def to_json(self):
        return _falcon_core.Domain_to_json(self)

    def hash(self):
        return _falcon_core.Domain_hash(self)
    __swig_destroy__ = _falcon_core.delete_Domain

# Register Domain in _falcon_core:
_falcon_core.Domain_swigregister(Domain)
class LabelledControlArray1D(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, array, label):
        _falcon_core.LabelledControlArray1D_swiginit(self, _falcon_core.new_LabelledControlArray1D(array, label))

    def get_array(self):
        return _falcon_core.LabelledControlArray1D_get_array(self)

    def to_json(self):
        return _falcon_core.LabelledControlArray1D_to_json(self)
    __swig_destroy__ = _falcon_core.delete_LabelledControlArray1D

# Register LabelledControlArray1D in _falcon_core:
_falcon_core.LabelledControlArray1D_swigregister(LabelledControlArray1D)
class IncreasingAlignment(Jsonable):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _falcon_core.IncreasingAlignment_swiginit(self, _falcon_core.new_IncreasingAlignment())

    def to_json(self):
        return _falcon_core.IncreasingAlignment_to_json(self)

    def hash(self):
        return _falcon_core.IncreasingAlignment_hash(self)
    __swig_destroy__ = _falcon_core.delete_IncreasingAlignment

# Register IncreasingAlignment in _falcon_core:
_falcon_core.IncreasingAlignment_swigregister(IncreasingAlignment)
class ControlArray1D(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, data):
        _falcon_core.ControlArray1D_swiginit(self, _falcon_core.new_ControlArray1D(data))

    def to_json(self):
        return _falcon_core.ControlArray1D_to_json(self)
    __swig_destroy__ = _falcon_core.delete_ControlArray1D

# Register ControlArray1D in _falcon_core:
_falcon_core.ControlArray1D_swigregister(ControlArray1D)
class QuantityDouble(Jsonable):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, value, unit):
        _falcon_core.QuantityDouble_swiginit(self, _falcon_core.new_QuantityDouble(value, unit))

    def value(self):
        return _falcon_core.QuantityDouble_value(self)

    def unit(self):
        return _falcon_core.QuantityDouble_unit(self)

    def to_json(self):
        return _falcon_core.QuantityDouble_to_json(self)

    def hash(self):
        return _falcon_core.QuantityDouble_hash(self)
    __swig_destroy__ = _falcon_core.delete_QuantityDouble

# Register QuantityDouble in _falcon_core:
_falcon_core.QuantityDouble_swigregister(QuantityDouble)
class BaseArrayDouble(Jsonable):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _falcon_core.BaseArrayDouble_swiginit(self, _falcon_core.new_BaseArrayDouble(*args))

    def data(self, *args):
        return _falcon_core.BaseArrayDouble_data(self, *args)

    def is_1d(self):
        return _falcon_core.BaseArrayDouble_is_1d(self)

    def to_json(self):
        return _falcon_core.BaseArrayDouble_to_json(self)

    def hash(self):
        return _falcon_core.BaseArrayDouble_hash(self)
    __swig_destroy__ = _falcon_core.delete_BaseArrayDouble

# Register BaseArrayDouble in _falcon_core:
_falcon_core.BaseArrayDouble_swigregister(BaseArrayDouble)
class ControlArrayDouble(BaseArrayDouble):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def to_json(self):
        return _falcon_core.ControlArrayDouble_to_json(self)

    def __init__(self):
        _falcon_core.ControlArrayDouble_swiginit(self, _falcon_core.new_ControlArrayDouble())
    __swig_destroy__ = _falcon_core.delete_ControlArrayDouble

# Register ControlArrayDouble in _falcon_core:
_falcon_core.ControlArrayDouble_swigregister(ControlArrayDouble)
class MeasuredArrayDouble(BaseArrayDouble):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def to_json(self):
        return _falcon_core.MeasuredArrayDouble_to_json(self)

    def __init__(self):
        _falcon_core.MeasuredArrayDouble_swiginit(self, _falcon_core.new_MeasuredArrayDouble())
    __swig_destroy__ = _falcon_core.delete_MeasuredArrayDouble

# Register MeasuredArrayDouble in _falcon_core:
_falcon_core.MeasuredArrayDouble_swigregister(MeasuredArrayDouble)
class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _falcon_core.delete_SwigPyIterator

    def value(self):
        return _falcon_core.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _falcon_core.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _falcon_core.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _falcon_core.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _falcon_core.SwigPyIterator_equal(self, x)

    def copy(self):
        return _falcon_core.SwigPyIterator_copy(self)

    def next(self):
        return _falcon_core.SwigPyIterator_next(self)

    def __next__(self):
        return _falcon_core.SwigPyIterator___next__(self)

    def previous(self):
        return _falcon_core.SwigPyIterator_previous(self)

    def advance(self, n):
        return _falcon_core.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _falcon_core.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _falcon_core.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _falcon_core.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _falcon_core.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _falcon_core.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _falcon_core.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _falcon_core:
_falcon_core.SwigPyIterator_swigregister(SwigPyIterator)
class AxesDomain(Jsonable):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _falcon_core.AxesDomain_swiginit(self, _falcon_core.new_AxesDomain(*args))

    def append(self, item):
        return _falcon_core.AxesDomain_append(self, item)

    def at(self, index):
        return _falcon_core.AxesDomain_at(self, index)

    def size(self):
        return _falcon_core.AxesDomain_size(self)

    def empty(self):
        return _falcon_core.AxesDomain_empty(self)

    def begin(self):
        return _falcon_core.AxesDomain_begin(self)

    def end(self):
        return _falcon_core.AxesDomain_end(self)

    def to_json(self):
        return _falcon_core.AxesDomain_to_json(self)

    def hash(self):
        return _falcon_core.AxesDomain_hash(self)
    __swig_destroy__ = _falcon_core.delete_AxesDomain

# Register AxesDomain in _falcon_core:
_falcon_core.AxesDomain_swigregister(AxesDomain)
class AxesMeasurementContext(Jsonable):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _falcon_core.AxesMeasurementContext_swiginit(self, _falcon_core.new_AxesMeasurementContext(*args))

    def append(self, item):
        return _falcon_core.AxesMeasurementContext_append(self, item)

    def at(self, index):
        return _falcon_core.AxesMeasurementContext_at(self, index)

    def size(self):
        return _falcon_core.AxesMeasurementContext_size(self)

    def empty(self):
        return _falcon_core.AxesMeasurementContext_empty(self)

    def begin(self):
        return _falcon_core.AxesMeasurementContext_begin(self)

    def end(self):
        return _falcon_core.AxesMeasurementContext_end(self)

    def to_json(self):
        return _falcon_core.AxesMeasurementContext_to_json(self)

    def hash(self):
        return _falcon_core.AxesMeasurementContext_hash(self)
    __swig_destroy__ = _falcon_core.delete_AxesMeasurementContext

# Register AxesMeasurementContext in _falcon_core:
_falcon_core.AxesMeasurementContext_swigregister(AxesMeasurementContext)
class LabelledDomainBC(Domain):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, min_val, max_val, label):
        _falcon_core.LabelledDomainBC_swiginit(self, _falcon_core.new_LabelledDomainBC(min_val, max_val, label))

    def label(self):
        return _falcon_core.LabelledDomainBC_label(self)

    def to_json(self):
        return _falcon_core.LabelledDomainBC_to_json(self)

    def hash(self):
        return _falcon_core.LabelledDomainBC_hash(self)
    __swig_destroy__ = _falcon_core.delete_LabelledDomainBC

# Register LabelledDomainBC in _falcon_core:
_falcon_core.LabelledDomainBC_swigregister(LabelledDomainBC)
class CoupledLabelledDomainBC(LabelledDomainBC):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, min_val, max_val, label, coupled_domains):
        _falcon_core.CoupledLabelledDomainBC_swiginit(self, _falcon_core.new_CoupledLabelledDomainBC(min_val, max_val, label, coupled_domains))

    def coupled_domains(self):
        return _falcon_core.CoupledLabelledDomainBC_coupled_domains(self)

    def to_json(self):
        return _falcon_core.CoupledLabelledDomainBC_to_json(self)

    def hash(self):
        return _falcon_core.CoupledLabelledDomainBC_hash(self)
    __swig_destroy__ = _falcon_core.delete_CoupledLabelledDomainBC

# Register CoupledLabelledDomainBC in _falcon_core:
_falcon_core.CoupledLabelledDomainBC_swigregister(CoupledLabelledDomainBC)
class BaseLabelledArraysLCA1D(Jsonable):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _falcon_core.BaseLabelledArraysLCA1D_swiginit(self, _falcon_core.new_BaseLabelledArraysLCA1D())

    def append(self, labelled_array):
        return _falcon_core.BaseLabelledArraysLCA1D_append(self, labelled_array)

    def get_arrays(self):
        return _falcon_core.BaseLabelledArraysLCA1D_get_arrays(self)

    def to_json(self):
        return _falcon_core.BaseLabelledArraysLCA1D_to_json(self)

    def hash(self):
        return _falcon_core.BaseLabelledArraysLCA1D_hash(self)
    __swig_destroy__ = _falcon_core.delete_BaseLabelledArraysLCA1D

# Register BaseLabelledArraysLCA1D in _falcon_core:
_falcon_core.BaseLabelledArraysLCA1D_swigregister(BaseLabelledArraysLCA1D)
class OneToOneMappingStringString(Jsonable):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _falcon_core.OneToOneMappingStringString_swiginit(self, _falcon_core.new_OneToOneMappingStringString())

    def insert(self, key, value):
        return _falcon_core.OneToOneMappingStringString_insert(self, key, value)

    def at_key(self, key):
        return _falcon_core.OneToOneMappingStringString_at_key(self, key)

    def at_value(self, value):
        return _falcon_core.OneToOneMappingStringString_at_value(self, value)

    def to_json(self):
        return _falcon_core.OneToOneMappingStringString_to_json(self)

    def hash(self):
        return _falcon_core.OneToOneMappingStringString_hash(self)
    __swig_destroy__ = _falcon_core.delete_OneToOneMappingStringString

# Register OneToOneMappingStringString in _falcon_core:
_falcon_core.OneToOneMappingStringString_swigregister(OneToOneMappingStringString)
class Channel(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def to_json(self):
        return _falcon_core.Channel_to_json(self)

    def __init__(self):
        _falcon_core.Channel_swiginit(self, _falcon_core.new_Channel())
    __swig_destroy__ = _falcon_core.delete_Channel

# Register Channel in _falcon_core:
_falcon_core.Channel_swigregister(Channel)
class BaseConnection(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def to_json(self):
        return _falcon_core.BaseConnection_to_json(self)

    def __init__(self):
        _falcon_core.BaseConnection_swiginit(self, _falcon_core.new_BaseConnection())
    __swig_destroy__ = _falcon_core.delete_BaseConnection

# Register BaseConnection in _falcon_core:
_falcon_core.BaseConnection_swigregister(BaseConnection)
class Gate(BaseConnection):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _falcon_core.Gate_swiginit(self, _falcon_core.new_Gate())

    def to_json(self):
        return _falcon_core.Gate_to_json(self)
    __swig_destroy__ = _falcon_core.delete_Gate

# Register Gate in _falcon_core:
_falcon_core.Gate_swigregister(Gate)
class Ohmic(BaseConnection):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _falcon_core.Ohmic_swiginit(self, _falcon_core.new_Ohmic())

    def to_json(self):
        return _falcon_core.Ohmic_to_json(self)
    __swig_destroy__ = _falcon_core.delete_Ohmic

# Register Ohmic in _falcon_core:
_falcon_core.Ohmic_swigregister(Ohmic)
class Impedance(Jsonable):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, impedance):
        _falcon_core.Impedance_swiginit(self, _falcon_core.new_Impedance(impedance))

    def get_impedance(self):
        return _falcon_core.Impedance_get_impedance(self)

    def to_json(self):
        return _falcon_core.Impedance_to_json(self)

    def hash(self):
        return _falcon_core.Impedance_hash(self)
    __swig_destroy__ = _falcon_core.delete_Impedance

# Register Impedance in _falcon_core:
_falcon_core.Impedance_swigregister(Impedance)
class Impedances(Jsonable):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _falcon_core.Impedances_swiginit(self, _falcon_core.new_Impedances())

    def append(self, impedance):
        return _falcon_core.Impedances_append(self, impedance)

    def to_json(self):
        return _falcon_core.Impedances_to_json(self)

    def hash(self):
        return _falcon_core.Impedances_hash(self)
    __swig_destroy__ = _falcon_core.delete_Impedances

# Register Impedances in _falcon_core:
_falcon_core.Impedances_swigregister(Impedances)
class GatePtrCompare(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __call__(self, lhs, rhs):
        return _falcon_core.GatePtrCompare___call__(self, lhs, rhs)

    def __init__(self):
        _falcon_core.GatePtrCompare_swiginit(self, _falcon_core.new_GatePtrCompare())
    __swig_destroy__ = _falcon_core.delete_GatePtrCompare

# Register GatePtrCompare in _falcon_core:
_falcon_core.GatePtrCompare_swigregister(GatePtrCompare)
class GateRelations(Jsonable):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _falcon_core.GateRelations_swiginit(self, _falcon_core.new_GateRelations())

    def insert(self, key, value):
        return _falcon_core.GateRelations_insert(self, key, value)

    def to_json(self):
        return _falcon_core.GateRelations_to_json(self)

    def hash(self):
        return _falcon_core.GateRelations_hash(self)
    __swig_destroy__ = _falcon_core.delete_GateRelations

# Register GateRelations in _falcon_core:
_falcon_core.GateRelations_swigregister(GateRelations)
class StandardConfigConnections(Jsonable):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, ohmics, gates):
        _falcon_core.StandardConfigConnections_swiginit(self, _falcon_core.new_StandardConfigConnections(ohmics, gates))

    def get_ohmics(self):
        return _falcon_core.StandardConfigConnections_get_ohmics(self)

    def get_gates(self):
        return _falcon_core.StandardConfigConnections_get_gates(self)

    def to_json(self):
        return _falcon_core.StandardConfigConnections_to_json(self)

    def hash(self):
        return _falcon_core.StandardConfigConnections_hash(self)
    __swig_destroy__ = _falcon_core.delete_StandardConfigConnections

# Register StandardConfigConnections in _falcon_core:
_falcon_core.StandardConfigConnections_swigregister(StandardConfigConnections)
class Loader(Jsonable):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, config):
        _falcon_core.Loader_swiginit(self, _falcon_core.new_Loader(config))

    def to_json(self):
        return _falcon_core.Loader_to_json(self)

    def hash(self):
        return _falcon_core.Loader_hash(self)
    __swig_destroy__ = _falcon_core.delete_Loader

# Register Loader in _falcon_core:
_falcon_core.Loader_swigregister(Loader)
class Channels(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def to_json(self):
        return _falcon_core.Channels_to_json(self)

    def __init__(self):
        _falcon_core.Channels_swiginit(self, _falcon_core.new_Channels())
    __swig_destroy__ = _falcon_core.delete_Channels

# Register Channels in _falcon_core:
_falcon_core.Channels_swigregister(Channels)
class NameBaseInt(Jsonable):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, name):
        _falcon_core.NameBaseInt_swiginit(self, _falcon_core.new_NameBaseInt(name))

    def name(self):
        return _falcon_core.NameBaseInt_name(self)

    def to_json(self):
        return _falcon_core.NameBaseInt_to_json(self)

    def hash(self):
        return _falcon_core.NameBaseInt_hash(self)
    __swig_destroy__ = _falcon_core.delete_NameBaseInt

# Register NameBaseInt in _falcon_core:
_falcon_core.NameBaseInt_swigregister(NameBaseInt)
class NameBaseString(Jsonable):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, name):
        _falcon_core.NameBaseString_swiginit(self, _falcon_core.new_NameBaseString(name))

    def name(self):
        return _falcon_core.NameBaseString_name(self)

    def to_json(self):
        return _falcon_core.NameBaseString_to_json(self)

    def hash(self):
        return _falcon_core.NameBaseString_hash(self)
    __swig_destroy__ = _falcon_core.delete_NameBaseString

# Register NameBaseString in _falcon_core:
_falcon_core.NameBaseString_swigregister(NameBaseString)
class Instrument(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _falcon_core.Instrument_swiginit(self, _falcon_core.new_Instrument())
    __swig_destroy__ = _falcon_core.delete_Instrument

# Register Instrument in _falcon_core:
_falcon_core.Instrument_swigregister(Instrument)
class InstrumentPortGate(Jsonable):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, default_name, pseudo_name, instrument_type, description):
        _falcon_core.InstrumentPortGate_swiginit(self, _falcon_core.new_InstrumentPortGate(default_name, pseudo_name, instrument_type, description))

    def default_name(self):
        return _falcon_core.InstrumentPortGate_default_name(self)

    def pseudo_name(self):
        return _falcon_core.InstrumentPortGate_pseudo_name(self)

    def to_json(self):
        return _falcon_core.InstrumentPortGate_to_json(self)

    def hash(self):
        return _falcon_core.InstrumentPortGate_hash(self)
    __swig_destroy__ = _falcon_core.delete_InstrumentPortGate

# Register InstrumentPortGate in _falcon_core:
_falcon_core.InstrumentPortGate_swigregister(InstrumentPortGate)
class PortsGate(Jsonable):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _falcon_core.PortsGate_swiginit(self, _falcon_core.new_PortsGate())

    def append(self, port):
        return _falcon_core.PortsGate_append(self, port)

    def get_ports(self):
        return _falcon_core.PortsGate_get_ports(self)

    def to_json(self):
        return _falcon_core.PortsGate_to_json(self)

    def hash(self):
        return _falcon_core.PortsGate_hash(self)
    __swig_destroy__ = _falcon_core.delete_PortsGate

# Register PortsGate in _falcon_core:
_falcon_core.PortsGate_swigregister(PortsGate)
class Gates(Jsonable):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _falcon_core.Gates_swiginit(self, _falcon_core.new_Gates())

    def append(self, connection):
        return _falcon_core.Gates_append(self, connection)

    def index(self, value):
        return _falcon_core.Gates_index(self, value)

    def get_connections(self):
        return _falcon_core.Gates_get_connections(self)

    def to_json(self):
        return _falcon_core.Gates_to_json(self)

    def hash(self):
        return _falcon_core.Gates_hash(self)
    __swig_destroy__ = _falcon_core.delete_Gates

# Register Gates in _falcon_core:
_falcon_core.Gates_swigregister(Gates)
class QuantityComplexDouble(Jsonable):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, value, unit):
        _falcon_core.QuantityComplexDouble_swiginit(self, _falcon_core.new_QuantityComplexDouble(value, unit))

    def value(self):
        return _falcon_core.QuantityComplexDouble_value(self)

    def unit(self):
        return _falcon_core.QuantityComplexDouble_unit(self)

    def to_json(self):
        return _falcon_core.QuantityComplexDouble_to_json(self)

    def hash(self):
        return _falcon_core.QuantityComplexDouble_hash(self)
    __swig_destroy__ = _falcon_core.delete_QuantityComplexDouble

# Register QuantityComplexDouble in _falcon_core:
_falcon_core.QuantityComplexDouble_swigregister(QuantityComplexDouble)
class Ohmics(Jsonable):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _falcon_core.Ohmics_swiginit(self, _falcon_core.new_Ohmics())

    def append(self, connection):
        return _falcon_core.Ohmics_append(self, connection)

    def index(self, value):
        return _falcon_core.Ohmics_index(self, value)

    def get_connections(self):
        return _falcon_core.Ohmics_get_connections(self)

    def to_json(self):
        return _falcon_core.Ohmics_to_json(self)

    def hash(self):
        return _falcon_core.Ohmics_hash(self)
    __swig_destroy__ = _falcon_core.delete_Ohmics

# Register Ohmics in _falcon_core:
_falcon_core.Ohmics_swigregister(Ohmics)
class AcquisitionContext(Jsonable):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _falcon_core.AcquisitionContext_swiginit(self, _falcon_core.new_AcquisitionContext())

    def to_json(self):
        return _falcon_core.AcquisitionContext_to_json(self)

    def hash(self):
        return _falcon_core.AcquisitionContext_hash(self)
    __swig_destroy__ = _falcon_core.delete_AcquisitionContext

# Register AcquisitionContext in _falcon_core:
_falcon_core.AcquisitionContext_swigregister(AcquisitionContext)
class MeasurementContext(Jsonable):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, connection, unit):
        _falcon_core.MeasurementContext_swiginit(self, _falcon_core.new_MeasurementContext(connection, unit))

    def connection(self):
        return _falcon_core.MeasurementContext_connection(self)

    def unit(self):
        return _falcon_core.MeasurementContext_unit(self)

    def to_json(self):
        return _falcon_core.MeasurementContext_to_json(self)

    def hash(self):
        return _falcon_core.MeasurementContext_hash(self)
    __swig_destroy__ = _falcon_core.delete_MeasurementContext

# Register MeasurementContext in _falcon_core:
_falcon_core.MeasurementContext_swigregister(MeasurementContext)
class InterpretationContext(Jsonable):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, independent_variables):
        _falcon_core.InterpretationContext_swiginit(self, _falcon_core.new_InterpretationContext(independent_variables))

    def to_json(self):
        return _falcon_core.InterpretationContext_to_json(self)

    def hash(self):
        return _falcon_core.InterpretationContext_hash(self)
    __swig_destroy__ = _falcon_core.delete_InterpretationContext

# Register InterpretationContext in _falcon_core:
_falcon_core.InterpretationContext_swigregister(InterpretationContext)
class InterpretationContextPtrCompare(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __call__(self, lhs, rhs):
        return _falcon_core.InterpretationContextPtrCompare___call__(self, lhs, rhs)

    def __init__(self):
        _falcon_core.InterpretationContextPtrCompare_swiginit(self, _falcon_core.new_InterpretationContextPtrCompare())
    __swig_destroy__ = _falcon_core.delete_InterpretationContextPtrCompare

# Register InterpretationContextPtrCompare in _falcon_core:
_falcon_core.InterpretationContextPtrCompare_swigregister(InterpretationContextPtrCompare)
class InterpretationContainerControlArray(Jsonable):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _falcon_core.InterpretationContainerControlArray_swiginit(self, _falcon_core.new_InterpretationContainerControlArray())

    def insert(self, context, value):
        return _falcon_core.InterpretationContainerControlArray_insert(self, context, value)

    def at(self, context):
        return _falcon_core.InterpretationContainerControlArray_at(self, context)

    def to_json(self):
        return _falcon_core.InterpretationContainerControlArray_to_json(self)

    def hash(self):
        return _falcon_core.InterpretationContainerControlArray_hash(self)
    __swig_destroy__ = _falcon_core.delete_InterpretationContainerControlArray

# Register InterpretationContainerControlArray in _falcon_core:
_falcon_core.InterpretationContainerControlArray_swigregister(InterpretationContainerControlArray)
class AnalyticFunction(Jsonable):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _falcon_core.delete_AnalyticFunction

    def evaluate(self, x):
        return _falcon_core.AnalyticFunction_evaluate(self, x)

    def to_json(self):
        return _falcon_core.AnalyticFunction_to_json(self)

    def hash(self):
        return _falcon_core.AnalyticFunction_hash(self)

# Register AnalyticFunction in _falcon_core:
_falcon_core.AnalyticFunction_swigregister(AnalyticFunction)
class PortTransform(Jsonable):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, function):
        _falcon_core.PortTransform_swiginit(self, _falcon_core.new_PortTransform(function))

    def apply(self, value):
        return _falcon_core.PortTransform_apply(self, value)

    def to_json(self):
        return _falcon_core.PortTransform_to_json(self)

    def hash(self):
        return _falcon_core.PortTransform_hash(self)
    __swig_destroy__ = _falcon_core.delete_PortTransform

# Register PortTransform in _falcon_core:
_falcon_core.PortTransform_swigregister(PortTransform)
class PortTransforms(Jsonable):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _falcon_core.PortTransforms_swiginit(self, _falcon_core.new_PortTransforms())

    def append(self, transform):
        return _falcon_core.PortTransforms_append(self, transform)

    def get_transforms(self):
        return _falcon_core.PortTransforms_get_transforms(self)

    def to_json(self):
        return _falcon_core.PortTransforms_to_json(self)

    def hash(self):
        return _falcon_core.PortTransforms_hash(self)
    __swig_destroy__ = _falcon_core.delete_PortTransforms

# Register PortTransforms in _falcon_core:
_falcon_core.PortTransforms_swigregister(PortTransforms)
class ConstantFunction(AnalyticFunction):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, value):
        _falcon_core.ConstantFunction_swiginit(self, _falcon_core.new_ConstantFunction(value))

    def evaluate(self, x):
        return _falcon_core.ConstantFunction_evaluate(self, x)

    def to_json(self):
        return _falcon_core.ConstantFunction_to_json(self)
    __swig_destroy__ = _falcon_core.delete_ConstantFunction

# Register ConstantFunction in _falcon_core:
_falcon_core.ConstantFunction_swigregister(ConstantFunction)
class Identity(AnalyticFunction):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _falcon_core.Identity_swiginit(self, _falcon_core.new_Identity())

    def evaluate(self, x):
        return _falcon_core.Identity_evaluate(self, x)

    def to_json(self):
        return _falcon_core.Identity_to_json(self)
    __swig_destroy__ = _falcon_core.delete_Identity

# Register Identity in _falcon_core:
_falcon_core.Identity_swigregister(Identity)
class IdentityTransform(PortTransform):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _falcon_core.IdentityTransform_swiginit(self, _falcon_core.new_IdentityTransform())

    def to_json(self):
        return _falcon_core.IdentityTransform_to_json(self)
    __swig_destroy__ = _falcon_core.delete_IdentityTransform

# Register IdentityTransform in _falcon_core:
_falcon_core.IdentityTransform_swigregister(IdentityTransform)
class BaseDiscretizer(Jsonable):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, delta, delta_domain):
        _falcon_core.BaseDiscretizer_swiginit(self, _falcon_core.new_BaseDiscretizer(delta, delta_domain))
    __swig_destroy__ = _falcon_core.delete_BaseDiscretizer

    def delta(self):
        return _falcon_core.BaseDiscretizer_delta(self)

    def set_delta(self, delta):
        return _falcon_core.BaseDiscretizer_set_delta(self, delta)

    def delta_domain(self):
        return _falcon_core.BaseDiscretizer_delta_domain(self)

    def to_json(self):
        return _falcon_core.BaseDiscretizer_to_json(self)

    def hash(self):
        return _falcon_core.BaseDiscretizer_hash(self)

# Register BaseDiscretizer in _falcon_core:
_falcon_core.BaseDiscretizer_swigregister(BaseDiscretizer)
class CartesianDiscretizer(BaseDiscretizer):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, delta, delta_domain):
        _falcon_core.CartesianDiscretizer_swiginit(self, _falcon_core.new_CartesianDiscretizer(delta, delta_domain))

    def to_json(self):
        return _falcon_core.CartesianDiscretizer_to_json(self)
    __swig_destroy__ = _falcon_core.delete_CartesianDiscretizer

# Register CartesianDiscretizer in _falcon_core:
_falcon_core.CartesianDiscretizer_swigregister(CartesianDiscretizer)
class Spaces(Jsonable):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _falcon_core.Spaces_swiginit(self, _falcon_core.new_Spaces())

    def append(self, space):
        return _falcon_core.Spaces_append(self, space)

    def get_spaces(self):
        return _falcon_core.Spaces_get_spaces(self)

    def to_json(self):
        return _falcon_core.Spaces_to_json(self)

    def hash(self):
        return _falcon_core.Spaces_hash(self)
    __swig_destroy__ = _falcon_core.delete_Spaces

# Register Spaces in _falcon_core:
_falcon_core.Spaces_swigregister(Spaces)
class Waveform(Jsonable):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, control_array, measured_array, spaces):
        _falcon_core.Waveform_swiginit(self, _falcon_core.new_Waveform(control_array, measured_array, spaces))

    def to_json(self):
        return _falcon_core.Waveform_to_json(self)

    def hash(self):
        return _falcon_core.Waveform_hash(self)
    __swig_destroy__ = _falcon_core.delete_Waveform

# Register Waveform in _falcon_core:
_falcon_core.Waveform_swigregister(Waveform)

# Move the wrapped C++ classes into their respective submodules
generic.Jsonable = Jsonable
del Jsonable

communications.Time = Time
del Time

physics.units.Dimension = Dimension
del Dimension
physics.units.Prefix = Prefix
del Prefix
physics.units.Sign = Sign
del Sign
physics.units.SymbolUnit = SymbolUnit
del SymbolUnit
physics.units.Unit = Unit
del Unit
physics.units.Units = Units
del Units

# Move math classes
math.QuantityDouble = QuantityDouble
del QuantityDouble
generic.OneToOneMappingStringString = OneToOneMappingStringString # Mapped to generic for now
del OneToOneMappingStringString
math.domains.Domain = Domain
del Domain
math.domains.LabelledDomain = LabelledDomainBC
del LabelledDomainBC
math.domains.CoupledLabelledDomain = CoupledLabelledDomainBC
del CoupledLabelledDomainBC

# Move array classes
math.arrays.BaseArray = BaseArrayDouble
del BaseArrayDouble
math.arrays.ControlArray = ControlArrayDouble
del ControlArrayDouble
math.arrays.MeasuredArray = MeasuredArrayDouble
del MeasuredArrayDouble
math.arrays.IncreasingAlignment = IncreasingAlignment
del IncreasingAlignment
math.arrays.ControlArray1D = ControlArray1D
del ControlArray1D

# Move labelled array classes
math.labelled_arrays.LabelledControlArray1D = LabelledControlArray1D
del LabelledControlArray1D
math.labelled_arrays.BaseLabelledArrays = BaseLabelledArraysLCA1D
del BaseLabelledArraysLCA1D

# Move axes classes
math.axes.AxesDomain = AxesDomain
del AxesDomain
math.axes.Axes = AxesMeasurementContext
del AxesMeasurementContext

# Move device classes
physics.device_structures.NameBaseInt = NameBaseInt
del NameBaseInt
physics.device_structures.NameBaseString = NameBaseString
del NameBaseString
physics.device_structures.Channel = Channel
del Channel
physics.device_structures.BaseConnection = BaseConnection
del BaseConnection
physics.device_structures.Gate = Gate
del Gate
physics.device_structures.Ohmic = Ohmic
del Ohmic
physics.device_structures.Gates = Gates
del Gates
physics.device_structures.Impedance = Impedance
del Impedance
physics.device_structures.Impedances = Impedances
del Impedances
physics.device_structures.GateRelations = GateRelations
del GateRelations
physics.device_structures.Ohmics = Ohmics
del Ohmics
physics.device_structures.Channels = Channels
del Channels

# Move config classes
physics.config.core.StandardConfigConnections = StandardConfigConnections
del StandardConfigConnections
physics.config.Loader = Loader
del Loader

# Move instrument and context classes
instrument_interfaces.names.InstrumentPort = InstrumentPortGate
del InstrumentPortGate
instrument_interfaces.names.Ports = PortsGate
del PortsGate
autotuner_interfaces.contexts.AcquisitionContext = AcquisitionContext
del AcquisitionContext
autotuner_interfaces.contexts.MeasurementContext = MeasurementContext
del MeasurementContext
autotuner_interfaces.interpretations.InterpretationContext = InterpretationContext
del InterpretationContext
autotuner_interfaces.interpretations.InterpretationContainer = InterpretationContainerControlArray
del InterpretationContainerControlArray

# Move transform classes
math.functions.AnalyticFunction = AnalyticFunction
del AnalyticFunction
math.functions.ConstantFunction = ConstantFunction
del ConstantFunction
math.functions.Identity = Identity
del Identity
physics.transforms.PortTransform = PortTransform
del PortTransform
physics.transforms.PortTransforms = PortTransforms
del PortTransforms
physics.transforms.IdentityTransform = IdentityTransform
del IdentityTransform

# Move waveform classes
math.discretizers.BaseDiscretizer = BaseDiscretizer
del BaseDiscretizer
math.discretizers.CartesianDiscretizer = CartesianDiscretizer
del CartesianDiscretizer
math.waveform.Spaces = Spaces
del Spaces
math.waveform.Waveform = Waveform
del Waveform


