# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.3.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _falcon_core
else:
    import _falcon_core

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import weakref


import sys
import importlib.util

# This code runs when the falcon_core module is imported.
# It creates the desired submodule structure in memory.
_pkg_name = __name__

# Create falcon_core.generic
_generic_spec = importlib.util.spec_from_loader(f'{_pkg_name}.generic', loader=None)
generic = importlib.util.module_from_spec(_generic_spec)
sys.modules[generic.__name__] = generic
setattr(sys.modules[_pkg_name], 'generic', generic)

# Create falcon_core.communications
_comm_spec = importlib.util.spec_from_loader(f'{_pkg_name}.communications', loader=None)
communications = importlib.util.module_from_spec(_comm_spec)
sys.modules[communications.__name__] = communications
setattr(sys.modules[_pkg_name], 'communications', communications)

# Create falcon_core.physics
_physics_spec = importlib.util.spec_from_loader(f'{_pkg_name}.physics', loader=None)
physics = importlib.util.module_from_spec(_physics_spec)
sys.modules[physics.__name__] = physics
setattr(sys.modules[_pkg_name], 'physics', physics)

# Create falcon_core.physics.units
_units_spec = importlib.util.spec_from_loader(f'{_pkg_name}.physics.units', loader=None)
physics.units = importlib.util.module_from_spec(_units_spec)
sys.modules[physics.units.__name__] = physics.units

# Create falcon_core.math
_math_spec = importlib.util.spec_from_loader(f'{_pkg_name}.math', loader=None)
math = importlib.util.module_from_spec(_math_spec)
sys.modules[math.__name__] = math
setattr(sys.modules[_pkg_name], 'math', math)

# Create falcon_core.math.domains
_domains_spec = importlib.util.spec_from_loader(f'{_pkg_name}.math.domains', loader=None)
math.domains = importlib.util.module_from_spec(_domains_spec)
sys.modules[math.domains.__name__] = math.domains

# Create falcon_core.math.arrays
_arrays_spec = importlib.util.spec_from_loader(f'{_pkg_name}.math.arrays', loader=None)
math.arrays = importlib.util.module_from_spec(_arrays_spec)
sys.modules[math.arrays.__name__] = math.arrays

# Create falcon_core.math.axes
_axes_spec = importlib.util.spec_from_loader(f'{_pkg_name}.math.axes', loader=None)
math.axes = importlib.util.module_from_spec(_axes_spec)
sys.modules[math.axes.__name__] = math.axes

# Create falcon_core.physics.device_structures
_devices_spec = importlib.util.spec_from_loader(f'{_pkg_name}.physics.device_structures', loader=None)
physics.device_structures = importlib.util.module_from_spec(_devices_spec)
sys.modules[physics.device_structures.__name__] = physics.device_structures

# Create falcon_core.physics.config
_config_spec = importlib.util.spec_from_loader(f'{_pkg_name}.physics.config', loader=None)
physics.config = importlib.util.module_from_spec(_config_spec)
sys.modules[physics.config.__name__] = physics.config

# Create falcon_core.physics.config.core
_config_core_spec = importlib.util.spec_from_loader(f'{_pkg_name}.physics.config.core', loader=None)
physics.config.core = importlib.util.module_from_spec(_config_core_spec)
sys.modules[physics.config.core.__name__] = physics.config.core

# Create falcon_core.instrument_interfaces
_instruments_spec = importlib.util.spec_from_loader(f'{_pkg_name}.instrument_interfaces', loader=None)
instrument_interfaces = importlib.util.module_from_spec(_instruments_spec)
sys.modules[instrument_interfaces.__name__] = instrument_interfaces
setattr(sys.modules[_pkg_name], 'instrument_interfaces', instrument_interfaces)

# Create falcon_core.instrument_interfaces.names
_instruments_names_spec = importlib.util.spec_from_loader(f'{_pkg_name}.instrument_interfaces.names', loader=None)
instrument_interfaces.names = importlib.util.module_from_spec(_instruments_names_spec)
sys.modules[instrument_interfaces.names.__name__] = instrument_interfaces.names

# Create falcon_core.autotuner_interfaces
_autotuner_spec = importlib.util.spec_from_loader(f'{_pkg_name}.autotuner_interfaces', loader=None)
autotuner_interfaces = importlib.util.module_from_spec(_autotuner_spec)
sys.modules[autotuner_interfaces.__name__] = autotuner_interfaces
setattr(sys.modules[_pkg_name], 'autotuner_interfaces', autotuner_interfaces)

# Create falcon_core.autotuner_interfaces.contexts
_contexts_spec = importlib.util.spec_from_loader(f'{_pkg_name}.autotuner_interfaces.contexts', loader=None)
autotuner_interfaces.contexts = importlib.util.module_from_spec(_contexts_spec)
sys.modules[autotuner_interfaces.contexts.__name__] = autotuner_interfaces.contexts

# Create falcon_core.autotuner_interfaces.interpretations
_interpretations_spec = importlib.util.spec_from_loader(f'{_pkg_name}.autotuner_interfaces.interpretations', loader=None)
autotuner_interfaces.interpretations = importlib.util.module_from_spec(_interpretations_spec)
sys.modules[autotuner_interfaces.interpretations.__name__] = autotuner_interfaces.interpretations

# Create falcon_core.math.functions
_functions_spec = importlib.util.spec_from_loader(f'{_pkg_name}.math.functions', loader=None)
math.functions = importlib.util.module_from_spec(_functions_spec)
sys.modules[math.functions.__name__] = math.functions

# Create falcon_core.physics.transforms
_transforms_spec = importlib.util.spec_from_loader(f'{_pkg_name}.physics.transforms', loader=None)
physics.transforms = importlib.util.module_from_spec(_transforms_spec)
sys.modules[physics.transforms.__name__] = physics.transforms

# Create falcon_core.math.discretizers
_discretizers_spec = importlib.util.spec_from_loader(f'{_pkg_name}.math.discretizers', loader=None)
math.discretizers = importlib.util.module_from_spec(_discretizers_spec)
sys.modules[math.discretizers.__name__] = math.discretizers

# Create falcon_core.math.waveform
_waveform_spec = importlib.util.spec_from_loader(f'{_pkg_name}.math.waveform', loader=None)
math.waveform = importlib.util.module_from_spec(_waveform_spec)
sys.modules[math.waveform.__name__] = math.waveform

# Create falcon_core.math.labelled_arrays
_labelled_arrays_spec = importlib.util.spec_from_loader(f'{_pkg_name}.math.labelled_arrays', loader=None)
math.labelled_arrays = importlib.util.module_from_spec(_labelled_arrays_spec)
sys.modules[math.labelled_arrays.__name__] = math.labelled_arrays

SHARED_PTR_DISOWN = _falcon_core.SHARED_PTR_DISOWN
class Song(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _falcon_core.delete_Song

    def to_json_string(self):
        return _falcon_core.Song_to_json_string(self)

    def to_json_stream(self, os):
        return _falcon_core.Song_to_json_stream(self, os)

    @staticmethod
    def from_json_string(json):
        return _falcon_core.Song_from_json_string(json)

    @staticmethod
    def from_json_stream(_is):
        return _falcon_core.Song_from_json_stream(_is)

    def __eq__(self, other):
        return _falcon_core.Song___eq__(self, other)

    def __init__(self):
        _falcon_core.Song_swiginit(self, _falcon_core.new_Song())

# Register Song in _falcon_core:
_falcon_core.Song_swigregister(Song)
class Unit(Song):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _falcon_core.Unit_swiginit(self, _falcon_core.new_Unit(*args))

    def prefix(self):
        return _falcon_core.Unit_prefix(self)

    def dimensions(self):
        return _falcon_core.Unit_dimensions(self)

    def scale_factor(self):
        return _falcon_core.Unit_scale_factor(self)

    def offset(self):
        return _falcon_core.Unit_offset(self)

    def __mul__(self, other):
        return _falcon_core.Unit___mul__(self, other)

    def __truediv__(self, *args):
        return _falcon_core.Unit___truediv__(self, *args)
    __div__ = __truediv__



    def __xor__(self, power):
        return _falcon_core.Unit___xor__(self, power)

    def with_prefix(self, prefix):
        return _falcon_core.Unit_with_prefix(self, prefix)

    def convert_value_to(self, value, target_unit):
        return _falcon_core.Unit_convert_value_to(self, value, target_unit)

    def is_compatible_with(self, other):
        return _falcon_core.Unit_is_compatible_with(self, other)
    __swig_destroy__ = _falcon_core.delete_Unit

# Register Unit in _falcon_core:
_falcon_core.Unit_swigregister(Unit)

def get_unit_with_prefix(unit, prefix):
    return _falcon_core.get_unit_with_prefix(unit, prefix)

def get_milli(unit):
    return _falcon_core.get_milli(unit)

def get_micro(unit):
    return _falcon_core.get_micro(unit)

def get_nano(unit):
    return _falcon_core.get_nano(unit)

def get_pico(unit):
    return _falcon_core.get_pico(unit)

def get_kilo(unit):
    return _falcon_core.get_kilo(unit)

def get_mega(unit):
    return _falcon_core.get_mega(unit)

def get_giga(unit):
    return _falcon_core.get_giga(unit)
class Prefix(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    @staticmethod
    def get_symbol(prefix_value):
        return _falcon_core.Prefix_get_symbol(prefix_value)

    @staticmethod
    def get_value(prefix_symbol):
        return _falcon_core.Prefix_get_value(prefix_symbol)

    @staticmethod
    def is_valid(prefix_symbol):
        return _falcon_core.Prefix_is_valid(prefix_symbol)

    @staticmethod
    def prefix_multiplication(first_prefix, second_prefix, scale_factor):
        return _falcon_core.Prefix_prefix_multiplication(first_prefix, second_prefix, scale_factor)

    def __init__(self):
        _falcon_core.Prefix_swiginit(self, _falcon_core.new_Prefix())
    __swig_destroy__ = _falcon_core.delete_Prefix

# Register Prefix in _falcon_core:
_falcon_core.Prefix_swigregister(Prefix)
cvar = _falcon_core.cvar
Meter = cvar.Meter
Kilogram = cvar.Kilogram
Second = cvar.Second
Ampere = cvar.Ampere
Kelvin = cvar.Kelvin
Mole = cvar.Mole
Candela = cvar.Candela
Hertz = cvar.Hertz
Newton = cvar.Newton
Pascal = cvar.Pascal
Joule = cvar.Joule
Watt = cvar.Watt
Coulomb = cvar.Coulomb
Volt = cvar.Volt
Farad = cvar.Farad
Ohm = cvar.Ohm
Siemens = cvar.Siemens
Weber = cvar.Weber
Tesla = cvar.Tesla
Henry = cvar.Henry
Minute = cvar.Minute
Hour = cvar.Hour
ElectronVolt = cvar.ElectronVolt
Celsius = cvar.Celsius
Fahrenheit = cvar.Fahrenheit
Dimensionless = cvar.Dimensionless
Percent = cvar.Percent
Radian = cvar.Radian
MilliMeter = cvar.MilliMeter
KiloMeter = cvar.KiloMeter
MilliVolt = cvar.MilliVolt
KiloVolt = cvar.KiloVolt
MilliAmpere = cvar.MilliAmpere
MicroAmpere = cvar.MicroAmpere
NanoAmpere = cvar.NanoAmpere
PicoAmpere = cvar.PicoAmpere
MilliSecond = cvar.MilliSecond
MicroSecond = cvar.MicroSecond
NanoSecond = cvar.NanoSecond
PicoSecond = cvar.PicoSecond
MilliOhm = cvar.MilliOhm
KiloOhm = cvar.KiloOhm
MegaOhm = cvar.MegaOhm
MilliHertz = cvar.MilliHertz
KiloHertz = cvar.KiloHertz
MegaHertz = cvar.MegaHertz
GigaHertz = cvar.GigaHertz
MetersPerSecond = cvar.MetersPerSecond
MetersPerSecondSquared = cvar.MetersPerSecondSquared
NewtonMeter = cvar.NewtonMeter
NewtonPerMeter = cvar.NewtonPerMeter
VoltsPerMeter = cvar.VoltsPerMeter
VoltsPerSecond = cvar.VoltsPerSecond
AmperesPerMeter = cvar.AmperesPerMeter
VoltsPerAmpere = cvar.VoltsPerAmpere
WattsPerMeterKelvin = cvar.WattsPerMeterKelvin
power_to_symbol = cvar.power_to_symbol
symbol_to_power = cvar.symbol_to_power

class SymbolUnit(Song):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, unit):
        _falcon_core.SymbolUnit_swiginit(self, _falcon_core.new_SymbolUnit(unit))

    def unit(self):
        return _falcon_core.SymbolUnit_unit(self)

    def symbol(self):
        return _falcon_core.SymbolUnit_symbol(self)

    def name(self):
        return _falcon_core.SymbolUnit_name(self)

    def __mul__(self, *args):
        return _falcon_core.SymbolUnit___mul__(self, *args)

    def __truediv__(self, *args):
        return _falcon_core.SymbolUnit___truediv__(self, *args)
    __div__ = __truediv__



    def __xor__(self, power):
        return _falcon_core.SymbolUnit___xor__(self, power)

    def with_prefix(self, prefix):
        return _falcon_core.SymbolUnit_with_prefix(self, prefix)

    def convert_value_to(self, value, target_unit):
        return _falcon_core.SymbolUnit_convert_value_to(self, value, target_unit)

    def is_compatible_with(self, other):
        return _falcon_core.SymbolUnit_is_compatible_with(self, other)
    __swig_destroy__ = _falcon_core.delete_SymbolUnit

# Register SymbolUnit in _falcon_core:
_falcon_core.SymbolUnit_swigregister(SymbolUnit)
_UNIT_SYMBOLS = cvar._UNIT_SYMBOLS
_DIMENSION_SYMBOLS = cvar._DIMENSION_SYMBOLS

class BaseConnection(Song):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, name):
        _falcon_core.BaseConnection_swiginit(self, _falcon_core.new_BaseConnection(name))

    def name(self):
        return _falcon_core.BaseConnection_name(self)
    __swig_destroy__ = _falcon_core.delete_BaseConnection

# Register BaseConnection in _falcon_core:
_falcon_core.BaseConnection_swigregister(BaseConnection)
class Gate(BaseConnection):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, name):
        _falcon_core.Gate_swiginit(self, _falcon_core.new_Gate(name))
    __swig_destroy__ = _falcon_core.delete_Gate

# Register Gate in _falcon_core:
_falcon_core.Gate_swigregister(Gate)
class DotGate(Gate):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, name):
        _falcon_core.DotGate_swiginit(self, _falcon_core.new_DotGate(name))
    __swig_destroy__ = _falcon_core.delete_DotGate

# Register DotGate in _falcon_core:
_falcon_core.DotGate_swigregister(DotGate)
class Ohmic(BaseConnection):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, name):
        _falcon_core.Ohmic_swiginit(self, _falcon_core.new_Ohmic(name))
    __swig_destroy__ = _falcon_core.delete_Ohmic

# Register Ohmic in _falcon_core:
_falcon_core.Ohmic_swigregister(Ohmic)
class BarrierGate(DotGate):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, name):
        _falcon_core.BarrierGate_swiginit(self, _falcon_core.new_BarrierGate(name))
    __swig_destroy__ = _falcon_core.delete_BarrierGate

# Register BarrierGate in _falcon_core:
_falcon_core.BarrierGate_swigregister(BarrierGate)
class PlungerGate(DotGate):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, name):
        _falcon_core.PlungerGate_swiginit(self, _falcon_core.new_PlungerGate(name))
    __swig_destroy__ = _falcon_core.delete_PlungerGate

# Register PlungerGate in _falcon_core:
_falcon_core.PlungerGate_swigregister(PlungerGate)
class ReservoirGate(Gate):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, name):
        _falcon_core.ReservoirGate_swiginit(self, _falcon_core.new_ReservoirGate(name))
    __swig_destroy__ = _falcon_core.delete_ReservoirGate

# Register ReservoirGate in _falcon_core:
_falcon_core.ReservoirGate_swigregister(ReservoirGate)
class ScreeningGate(Gate):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, name):
        _falcon_core.ScreeningGate_swiginit(self, _falcon_core.new_ScreeningGate(name))
    __swig_destroy__ = _falcon_core.delete_ScreeningGate

# Register ScreeningGate in _falcon_core:
_falcon_core.ScreeningGate_swigregister(ScreeningGate)
class Impedance(Song):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, connection, resistance, capacitance):
        _falcon_core.Impedance_swiginit(self, _falcon_core.new_Impedance(connection, resistance, capacitance))

    def connection(self):
        return _falcon_core.Impedance_connection(self)

    def resistance(self):
        return _falcon_core.Impedance_resistance(self)

    def capacitance(self):
        return _falcon_core.Impedance_capacitance(self)
    __swig_destroy__ = _falcon_core.delete_Impedance

# Register Impedance in _falcon_core:
_falcon_core.Impedance_swigregister(Impedance)

# Move the wrapped C++ classes into their respective submodules
generic.Jsonable = Jsonable
del Jsonable

communications.Time = Time
del Time

physics.units.Dimension = Dimension
del Dimension
physics.units.Prefix = Prefix
del Prefix
physics.units.Sign = Sign
del Sign
physics.units.SymbolUnit = SymbolUnit
del SymbolUnit
physics.units.Unit = Unit
del Unit
physics.units.Units = Units
del Units

# Move math classes
math.QuantityDouble = QuantityDouble
del QuantityDouble
generic.OneToOneMappingStringString = OneToOneMappingStringString # Mapped to generic for now
del OneToOneMappingStringString
math.domains.Domain = Domain
del Domain
math.domains.LabelledDomain = LabelledDomainBC
del LabelledDomainBC
math.domains.CoupledLabelledDomain = CoupledLabelledDomainBC
del CoupledLabelledDomainBC

# Move array classes
math.arrays.BaseArray = BaseArrayDouble
del BaseArrayDouble
math.arrays.ControlArray = ControlArrayDouble
del ControlArrayDouble
math.arrays.MeasuredArray = MeasuredArrayDouble
del MeasuredArrayDouble
math.arrays.IncreasingAlignment = IncreasingAlignment
del IncreasingAlignment
math.arrays.ControlArray1D = ControlArray1D
del ControlArray1D

# Move labelled array classes
math.labelled_arrays.LabelledControlArray1D = LabelledControlArray1D
del LabelledControlArray1D
math.labelled_arrays.BaseLabelledArrays = BaseLabelledArraysLCA1D
del BaseLabelledArraysLCA1D

# Move axes classes
math.axes.AxesDomain = AxesDomain
del AxesDomain
math.axes.Axes = AxesMeasurementContext
del AxesMeasurementContext

# Move device classes
physics.device_structures.NameBaseInt = NameBaseInt
del NameBaseInt
physics.device_structures.NameBaseString = NameBaseString
del NameBaseString
physics.device_structures.Channel = Channel
del Channel
physics.device_structures.BaseConnection = BaseConnection
del BaseConnection
physics.device_structures.Gate = Gate
del Gate
physics.device_structures.Ohmic = Ohmic
del Ohmic
physics.device_structures.Gates = Gates
del Gates
physics.device_structures.Impedance = Impedance
del Impedance
physics.device_structures.Impedances = Impedances
del Impedances
physics.device_structures.GateRelations = GateRelations
del GateRelations
physics.device_structures.Ohmics = Ohmics
del Ohmics
physics.device_structures.Channels = Channels
del Channels

# Move config classes
physics.config.core.StandardConfigConnections = StandardConfigConnections
del StandardConfigConnections
physics.config.Loader = Loader
del Loader

# Move instrument and context classes
instrument_interfaces.names.InstrumentPort = InstrumentPortGate
del InstrumentPortGate
instrument_interfaces.names.Ports = PortsGate
del PortsGate
autotuner_interfaces.contexts.AcquisitionContext = AcquisitionContext
del AcquisitionContext
autotuner_interfaces.contexts.MeasurementContext = MeasurementContext
del MeasurementContext
autotuner_interfaces.interpretations.InterpretationContext = InterpretationContext
del InterpretationContext
autotuner_interfaces.interpretations.InterpretationContainer = InterpretationContainerControlArray
del InterpretationContainerControlArray

# Move transform classes
math.functions.AnalyticFunction = AnalyticFunction
del AnalyticFunction
math.functions.ConstantFunction = ConstantFunction
del ConstantFunction
math.functions.Identity = Identity
del Identity
physics.transforms.PortTransform = PortTransform
del PortTransform
physics.transforms.PortTransforms = PortTransforms
del PortTransforms
physics.transforms.IdentityTransform = IdentityTransform
del IdentityTransform

# Move waveform classes
math.discretizers.BaseDiscretizer = BaseDiscretizer
del BaseDiscretizer
math.discretizers.CartesianDiscretizer = CartesianDiscretizer
del CartesianDiscretizer
math.waveform.Spaces = Spaces
del Spaces
math.waveform.Waveform = Waveform
del Waveform


