# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.3.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _falcon_core
else:
    import _falcon_core

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import weakref

SHARED_PTR_DISOWN = _falcon_core.SHARED_PTR_DISOWN
class Song(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _falcon_core.delete_Song

    def to_json_string(self):
        return _falcon_core.Song_to_json_string(self)

    def to_json_stream(self, os):
        return _falcon_core.Song_to_json_stream(self, os)

    def __eq__(self, other):
        return _falcon_core.Song___eq__(self, other)

    def repr(self):
        return _falcon_core.Song_repr(self)

    def __init__(self):
        if self.__class__ == Song:
            _self = None
        else:
            _self = self
        _falcon_core.Song_swiginit(self, _falcon_core.new_Song(_self, ))
    def __disown__(self):
        self.this.disown()
        _falcon_core.disown_Song(self)
        return weakref.proxy(self)

# Register Song in _falcon_core:
_falcon_core.Song_swigregister(Song)
class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _falcon_core.delete_SwigPyIterator

    def value(self):
        return _falcon_core.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _falcon_core.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _falcon_core.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _falcon_core.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _falcon_core.SwigPyIterator_equal(self, x)

    def copy(self):
        return _falcon_core.SwigPyIterator_copy(self)

    def next(self):
        return _falcon_core.SwigPyIterator_next(self)

    def __next__(self):
        return _falcon_core.SwigPyIterator___next__(self)

    def previous(self):
        return _falcon_core.SwigPyIterator_previous(self)

    def advance(self, n):
        return _falcon_core.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _falcon_core.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _falcon_core.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _falcon_core.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _falcon_core.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _falcon_core.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _falcon_core.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _falcon_core:
_falcon_core.SwigPyIterator_swigregister(SwigPyIterator)
class SymbolToPowerMap(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _falcon_core.SymbolToPowerMap_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _falcon_core.SymbolToPowerMap___nonzero__(self)

    def __bool__(self):
        return _falcon_core.SymbolToPowerMap___bool__(self)

    def __len__(self):
        return _falcon_core.SymbolToPowerMap___len__(self)
    def __iter__(self):
        return self.key_iterator()
    def iterkeys(self):
        return self.key_iterator()
    def itervalues(self):
        return self.value_iterator()
    def iteritems(self):
        return self.iterator()

    def __getitem__(self, key):
        return _falcon_core.SymbolToPowerMap___getitem__(self, key)

    def __delitem__(self, key):
        return _falcon_core.SymbolToPowerMap___delitem__(self, key)

    def has_key(self, key):
        return _falcon_core.SymbolToPowerMap_has_key(self, key)

    def keys(self):
        return _falcon_core.SymbolToPowerMap_keys(self)

    def values(self):
        return _falcon_core.SymbolToPowerMap_values(self)

    def items(self):
        return _falcon_core.SymbolToPowerMap_items(self)

    def __contains__(self, key):
        return _falcon_core.SymbolToPowerMap___contains__(self, key)

    def key_iterator(self):
        return _falcon_core.SymbolToPowerMap_key_iterator(self)

    def value_iterator(self):
        return _falcon_core.SymbolToPowerMap_value_iterator(self)

    def __setitem__(self, *args):
        return _falcon_core.SymbolToPowerMap___setitem__(self, *args)

    def asdict(self):
        return _falcon_core.SymbolToPowerMap_asdict(self)

    def __init__(self, *args):
        _falcon_core.SymbolToPowerMap_swiginit(self, _falcon_core.new_SymbolToPowerMap(*args))

    def empty(self):
        return _falcon_core.SymbolToPowerMap_empty(self)

    def size(self):
        return _falcon_core.SymbolToPowerMap_size(self)

    def swap(self, v):
        return _falcon_core.SymbolToPowerMap_swap(self, v)

    def begin(self):
        return _falcon_core.SymbolToPowerMap_begin(self)

    def end(self):
        return _falcon_core.SymbolToPowerMap_end(self)

    def rbegin(self):
        return _falcon_core.SymbolToPowerMap_rbegin(self)

    def rend(self):
        return _falcon_core.SymbolToPowerMap_rend(self)

    def clear(self):
        return _falcon_core.SymbolToPowerMap_clear(self)

    def get_allocator(self):
        return _falcon_core.SymbolToPowerMap_get_allocator(self)

    def count(self, x):
        return _falcon_core.SymbolToPowerMap_count(self, x)

    def erase(self, *args):
        return _falcon_core.SymbolToPowerMap_erase(self, *args)

    def find(self, x):
        return _falcon_core.SymbolToPowerMap_find(self, x)

    def lower_bound(self, x):
        return _falcon_core.SymbolToPowerMap_lower_bound(self, x)

    def upper_bound(self, x):
        return _falcon_core.SymbolToPowerMap_upper_bound(self, x)
    __swig_destroy__ = _falcon_core.delete_SymbolToPowerMap

# Register SymbolToPowerMap in _falcon_core:
_falcon_core.SymbolToPowerMap_swigregister(SymbolToPowerMap)
class PowerToSymbolMap(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _falcon_core.PowerToSymbolMap_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _falcon_core.PowerToSymbolMap___nonzero__(self)

    def __bool__(self):
        return _falcon_core.PowerToSymbolMap___bool__(self)

    def __len__(self):
        return _falcon_core.PowerToSymbolMap___len__(self)
    def __iter__(self):
        return self.key_iterator()
    def iterkeys(self):
        return self.key_iterator()
    def itervalues(self):
        return self.value_iterator()
    def iteritems(self):
        return self.iterator()

    def __getitem__(self, key):
        return _falcon_core.PowerToSymbolMap___getitem__(self, key)

    def __delitem__(self, key):
        return _falcon_core.PowerToSymbolMap___delitem__(self, key)

    def has_key(self, key):
        return _falcon_core.PowerToSymbolMap_has_key(self, key)

    def keys(self):
        return _falcon_core.PowerToSymbolMap_keys(self)

    def values(self):
        return _falcon_core.PowerToSymbolMap_values(self)

    def items(self):
        return _falcon_core.PowerToSymbolMap_items(self)

    def __contains__(self, key):
        return _falcon_core.PowerToSymbolMap___contains__(self, key)

    def key_iterator(self):
        return _falcon_core.PowerToSymbolMap_key_iterator(self)

    def value_iterator(self):
        return _falcon_core.PowerToSymbolMap_value_iterator(self)

    def __setitem__(self, *args):
        return _falcon_core.PowerToSymbolMap___setitem__(self, *args)

    def asdict(self):
        return _falcon_core.PowerToSymbolMap_asdict(self)

    def __init__(self, *args):
        _falcon_core.PowerToSymbolMap_swiginit(self, _falcon_core.new_PowerToSymbolMap(*args))

    def empty(self):
        return _falcon_core.PowerToSymbolMap_empty(self)

    def size(self):
        return _falcon_core.PowerToSymbolMap_size(self)

    def swap(self, v):
        return _falcon_core.PowerToSymbolMap_swap(self, v)

    def begin(self):
        return _falcon_core.PowerToSymbolMap_begin(self)

    def end(self):
        return _falcon_core.PowerToSymbolMap_end(self)

    def rbegin(self):
        return _falcon_core.PowerToSymbolMap_rbegin(self)

    def rend(self):
        return _falcon_core.PowerToSymbolMap_rend(self)

    def clear(self):
        return _falcon_core.PowerToSymbolMap_clear(self)

    def get_allocator(self):
        return _falcon_core.PowerToSymbolMap_get_allocator(self)

    def count(self, x):
        return _falcon_core.PowerToSymbolMap_count(self, x)

    def erase(self, *args):
        return _falcon_core.PowerToSymbolMap_erase(self, *args)

    def find(self, x):
        return _falcon_core.PowerToSymbolMap_find(self, x)

    def lower_bound(self, x):
        return _falcon_core.PowerToSymbolMap_lower_bound(self, x)

    def upper_bound(self, x):
        return _falcon_core.PowerToSymbolMap_upper_bound(self, x)
    __swig_destroy__ = _falcon_core.delete_PowerToSymbolMap

# Register PowerToSymbolMap in _falcon_core:
_falcon_core.PowerToSymbolMap_swigregister(PowerToSymbolMap)
class Unit(Song):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _falcon_core.Unit_swiginit(self, _falcon_core.new_Unit(*args))

    def prefix(self):
        return _falcon_core.Unit_prefix(self)

    def dimensions(self):
        return _falcon_core.Unit_dimensions(self)

    def scale_factor(self):
        return _falcon_core.Unit_scale_factor(self)

    def offset(self):
        return _falcon_core.Unit_offset(self)

    def __mul__(self, other):
        return _falcon_core.Unit___mul__(self, other)

    def __truediv__(self, *args):
        return _falcon_core.Unit___truediv__(self, *args)
    __div__ = __truediv__



    def __xor__(self, power):
        return _falcon_core.Unit___xor__(self, power)

    def with_prefix(self, prefix):
        return _falcon_core.Unit_with_prefix(self, prefix)

    def convert_value_to(self, value, target_unit):
        return _falcon_core.Unit_convert_value_to(self, value, target_unit)

    def is_compatible_with(self, other):
        return _falcon_core.Unit_is_compatible_with(self, other)
    __swig_destroy__ = _falcon_core.delete_Unit

# Register Unit in _falcon_core:
_falcon_core.Unit_swigregister(Unit)

def get_unit_with_prefix(unit, prefix):
    return _falcon_core.get_unit_with_prefix(unit, prefix)

def get_milli(unit):
    return _falcon_core.get_milli(unit)

def get_micro(unit):
    return _falcon_core.get_micro(unit)

def get_nano(unit):
    return _falcon_core.get_nano(unit)

def get_pico(unit):
    return _falcon_core.get_pico(unit)

def get_kilo(unit):
    return _falcon_core.get_kilo(unit)

def get_mega(unit):
    return _falcon_core.get_mega(unit)

def get_giga(unit):
    return _falcon_core.get_giga(unit)
class Prefix(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    @staticmethod
    def symbol_to_power():
        return _falcon_core.Prefix_symbol_to_power()

    @staticmethod
    def power_to_symbol():
        return _falcon_core.Prefix_power_to_symbol()

    @staticmethod
    def get_symbol(prefix_value):
        return _falcon_core.Prefix_get_symbol(prefix_value)

    @staticmethod
    def get_value(prefix_symbol):
        return _falcon_core.Prefix_get_value(prefix_symbol)

    @staticmethod
    def is_valid(prefix_symbol):
        return _falcon_core.Prefix_is_valid(prefix_symbol)

    @staticmethod
    def prefix_multiplication(first_prefix, second_prefix, scale_factor):
        return _falcon_core.Prefix_prefix_multiplication(first_prefix, second_prefix, scale_factor)

    def __init__(self):
        _falcon_core.Prefix_swiginit(self, _falcon_core.new_Prefix())
    __swig_destroy__ = _falcon_core.delete_Prefix

# Register Prefix in _falcon_core:
_falcon_core.Prefix_swigregister(Prefix)
cvar = _falcon_core.cvar
Meter = cvar.Meter
Kilogram = cvar.Kilogram
Second = cvar.Second
Ampere = cvar.Ampere
Kelvin = cvar.Kelvin
Mole = cvar.Mole
Candela = cvar.Candela
Hertz = cvar.Hertz
Newton = cvar.Newton
Pascal = cvar.Pascal
Joule = cvar.Joule
Watt = cvar.Watt
Coulomb = cvar.Coulomb
Volt = cvar.Volt
Farad = cvar.Farad
Ohm = cvar.Ohm
Siemens = cvar.Siemens
Weber = cvar.Weber
Tesla = cvar.Tesla
Henry = cvar.Henry
Minute = cvar.Minute
Hour = cvar.Hour
ElectronVolt = cvar.ElectronVolt
Celsius = cvar.Celsius
Fahrenheit = cvar.Fahrenheit
Dimensionless = cvar.Dimensionless
Percent = cvar.Percent
Radian = cvar.Radian
MilliMeter = cvar.MilliMeter
KiloMeter = cvar.KiloMeter
MilliVolt = cvar.MilliVolt
KiloVolt = cvar.KiloVolt
MilliAmpere = cvar.MilliAmpere
MicroAmpere = cvar.MicroAmpere
NanoAmpere = cvar.NanoAmpere
PicoAmpere = cvar.PicoAmpere
MilliSecond = cvar.MilliSecond
MicroSecond = cvar.MicroSecond
NanoSecond = cvar.NanoSecond
PicoSecond = cvar.PicoSecond
MilliOhm = cvar.MilliOhm
KiloOhm = cvar.KiloOhm
MegaOhm = cvar.MegaOhm
MilliHertz = cvar.MilliHertz
KiloHertz = cvar.KiloHertz
MegaHertz = cvar.MegaHertz
GigaHertz = cvar.GigaHertz
MetersPerSecond = cvar.MetersPerSecond
MetersPerSecondSquared = cvar.MetersPerSecondSquared
NewtonMeter = cvar.NewtonMeter
NewtonPerMeter = cvar.NewtonPerMeter
VoltsPerMeter = cvar.VoltsPerMeter
VoltsPerSecond = cvar.VoltsPerSecond
AmperesPerMeter = cvar.AmperesPerMeter
VoltsPerAmpere = cvar.VoltsPerAmpere
WattsPerMeterKelvin = cvar.WattsPerMeterKelvin

class SymbolUnit(Song):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, unit):
        _falcon_core.SymbolUnit_swiginit(self, _falcon_core.new_SymbolUnit(unit))

    def unit(self):
        return _falcon_core.SymbolUnit_unit(self)

    def symbol(self):
        return _falcon_core.SymbolUnit_symbol(self)

    def name(self):
        return _falcon_core.SymbolUnit_name(self)

    def __mul__(self, *args):
        return _falcon_core.SymbolUnit___mul__(self, *args)

    def __truediv__(self, *args):
        return _falcon_core.SymbolUnit___truediv__(self, *args)
    __div__ = __truediv__



    def __xor__(self, power):
        return _falcon_core.SymbolUnit___xor__(self, power)

    def with_prefix(self, prefix):
        return _falcon_core.SymbolUnit_with_prefix(self, prefix)

    def convert_value_to(self, value, target_unit):
        return _falcon_core.SymbolUnit_convert_value_to(self, value, target_unit)

    def is_compatible_with(self, other):
        return _falcon_core.SymbolUnit_is_compatible_with(self, other)

    def str(self):
        return _falcon_core.SymbolUnit_str(self)
    __swig_destroy__ = _falcon_core.delete_SymbolUnit

# Register SymbolUnit in _falcon_core:
_falcon_core.SymbolUnit_swigregister(SymbolUnit)
class BaseConnection(Song):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __lt__(self, other):
        return _falcon_core.BaseConnection___lt__(self, other)

    def __init__(self, name):
        _falcon_core.BaseConnection_swiginit(self, _falcon_core.new_BaseConnection(name))

    def name(self):
        return _falcon_core.BaseConnection_name(self)
    __swig_destroy__ = _falcon_core.delete_BaseConnection

# Register BaseConnection in _falcon_core:
_falcon_core.BaseConnection_swigregister(BaseConnection)
class Gate(BaseConnection):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, name):
        _falcon_core.Gate_swiginit(self, _falcon_core.new_Gate(name))
    __swig_destroy__ = _falcon_core.delete_Gate

# Register Gate in _falcon_core:
_falcon_core.Gate_swigregister(Gate)
class DotGate(Gate):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, name):
        _falcon_core.DotGate_swiginit(self, _falcon_core.new_DotGate(name))
    __swig_destroy__ = _falcon_core.delete_DotGate

# Register DotGate in _falcon_core:
_falcon_core.DotGate_swigregister(DotGate)
class Ohmic(BaseConnection):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, name):
        _falcon_core.Ohmic_swiginit(self, _falcon_core.new_Ohmic(name))
    __swig_destroy__ = _falcon_core.delete_Ohmic

# Register Ohmic in _falcon_core:
_falcon_core.Ohmic_swigregister(Ohmic)
class BarrierGate(DotGate):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, name):
        _falcon_core.BarrierGate_swiginit(self, _falcon_core.new_BarrierGate(name))
    __swig_destroy__ = _falcon_core.delete_BarrierGate

# Register BarrierGate in _falcon_core:
_falcon_core.BarrierGate_swigregister(BarrierGate)
class PlungerGate(DotGate):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, name):
        _falcon_core.PlungerGate_swiginit(self, _falcon_core.new_PlungerGate(name))
    __swig_destroy__ = _falcon_core.delete_PlungerGate

# Register PlungerGate in _falcon_core:
_falcon_core.PlungerGate_swigregister(PlungerGate)
class ReservoirGate(Gate):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, name):
        _falcon_core.ReservoirGate_swiginit(self, _falcon_core.new_ReservoirGate(name))
    __swig_destroy__ = _falcon_core.delete_ReservoirGate

# Register ReservoirGate in _falcon_core:
_falcon_core.ReservoirGate_swigregister(ReservoirGate)
class ScreeningGate(Gate):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, name):
        _falcon_core.ScreeningGate_swiginit(self, _falcon_core.new_ScreeningGate(name))
    __swig_destroy__ = _falcon_core.delete_ScreeningGate

# Register ScreeningGate in _falcon_core:
_falcon_core.ScreeningGate_swigregister(ScreeningGate)
class Impedance(Song):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, connection, resistance, capacitance):
        _falcon_core.Impedance_swiginit(self, _falcon_core.new_Impedance(connection, resistance, capacitance))

    def connection(self):
        return _falcon_core.Impedance_connection(self)

    def resistance(self):
        return _falcon_core.Impedance_resistance(self)

    def capacitance(self):
        return _falcon_core.Impedance_capacitance(self)
    __swig_destroy__ = _falcon_core.delete_Impedance

# Register Impedance in _falcon_core:
_falcon_core.Impedance_swigregister(Impedance)

# C++ classes are placed into their submodules using SWIG's %rename directive.


