- comment_raw: "/**\n   * @brief Constructor for config loading utility.\n   * @param\
    \ config_path Path to the configuration file.\n   */"
  comment: '@brief Constructor for config loading utility.

    @param config_path Path to the configuration file.'
  declaration: Loader(const boost::filesystem::path& config_path);
  kind: function
  name: falcon_core::physics::config::Loader
- comment_raw: "/**\n   * @brief Constructor for config loading utility.\n   * @param\
    \ config_path Complete Path to the configuration file.\n   */"
  comment: '@brief Constructor for config loading utility.

    @param config_path Complete Path to the configuration file.'
  declaration: Loader(const std::string config_path);
  kind: function
  name: falcon_core::physics::config::Loader
- comment_raw: "/**\n   * @brief Loads the config file into nodes.\n   */"
  comment: '@brief Loads the config file into nodes.'
  declaration: core::ConfigSP _load_config();
  kind: function
  name: falcon_core::physics::config::Loader::_load_config
- comment_raw: "/**\n   * @brief Returns the config.\n   */"
  comment: '@brief Returns the config.'
  declaration: core::ConfigSP config() const;
  kind: function
  name: falcon_core::physics::config::Loader::config
