c_header: GateGeometryArray1D_c_api.h
cpp_headers:
- ../../../../../../cpp/include/falcon_core/physics/config/geometries/GateGeometryArray1D.hpp
mappings:
- cpp: falcon_core::physics::config::geometries::GateGeometryArray1D::append_central_gate
  c: GateGeometryArray1D_append_central_gate
- cpp: falcon_core::physics::config::geometries::GateGeometryArray1D::all_dot_gates
  c: GateGeometryArray1D_all_dot_gates
- cpp: falcon_core::physics::config::geometries::GateGeometryArray1D::query_neighbors
  c: GateGeometryArray1D_query_neighbors
- cpp: falcon_core::physics::config::geometries::GateGeometryArray1D::left_reservoir
  c: GateGeometryArray1D_left_reservoir
- cpp: falcon_core::physics::config::geometries::GateGeometryArray1D::right_reservoir
  c: GateGeometryArray1D_right_reservoir
- cpp: falcon_core::physics::config::geometries::GateGeometryArray1D::left_barrier
  c: GateGeometryArray1D_left_barrier
- cpp: falcon_core::physics::config::geometries::GateGeometryArray1D::right_barrier
  c: GateGeometryArray1D_right_barrier
- cpp: falcon_core::physics::config::geometries::GateGeometryArray1D::lineararray
  c: GateGeometryArray1D_linear_array
- cpp: falcon_core::physics::config::geometries::GateGeometryArray1D::screening_gates
  c: GateGeometryArray1D_screening_gates
- cpp: falcon_core::physics::config::geometries::GateGeometryArray1D::raw_central_gates
  c: GateGeometryArray1D_raw_central_gates
- cpp: falcon_core::physics::config::geometries::GateGeometryArray1D::central_dot_gates
  c: GateGeometryArray1D_central_dot_gates
- cpp: falcon_core::physics::config::geometries::GateGeometryArray1D::ohmics
  c: GateGeometryArray1D_ohmics
